### ISSUE TITLE
Change http: to https: in sourcecode 

### ISSUE THREAD

**Issue by desawarna** [eprints/eprints3.4#104]
I want to change **http:** to **https:** in the eprints source code, 
where should I change the source code file?
![Screenshot from 2020-10-27 08-18-08](https://user-images.githubusercontent.com/1111630/97245379-e2108980-1835-11eb-9d08-22342f2aeb68.png)

[https://support.mozilla.org/en-US/kb/mixed-content-blocking-firefox](https://support.mozilla.org/en-US/kb/mixed-content-blocking-firefox)

**Comment by drn05r** [comment]
You need to configure HTTPS.  Instructions can be found here:

https://wiki.eprints.org/w/How_to_use_EPrints_with_HTTPS

However, if you are running 3.4.1+ it is worth using the instructions designed for more recent versions of EPrints that makes it easy to configure HTTPS as compulsory for all pages or just for those that require the user to be logged in (whilst allowing you to access public unauthenticated pages over HTTP or HTTPS):

https://wiki.eprints.org/w/Simplified_HTTPS_Configuration
