### ISSUE TITLE
How To Run generate_apacheconf

### ISSUE THREAD

**Issue by desawarna** [eprints/eprints3.4#108]
How To Run generate_apacheconf ?
I run `sudo ./generate_apacheconf` , error

![Screenshot from 2020-11-03 08-47-20](https://user-images.githubusercontent.com/1111630/97937493-d2ef8580-1db9-11eb-83a5-7d8b3ad7ee82.png)

**Comment by drn05r** [comment]
You must run this command as the eprints users.  If you have installed EPrints from its DEB or RPM package then this user will have been create so do the following:

sudo su eprints
/usr/share/eprints/bin/generate_apacheconf --system --replace

The --system --replace are probably not necessary if this if the first time you are running generate_apacheconf but are good to include generally.

GitHub issues tracker is really for reporting bugs or feature requests.  If you need help installing EPrints look at the wiki at https://wiki.eprints.org or subscribe to the EPrints Tech mailing list.  Instructions for how to do the latter can be found at:

http://mailman.ecs.soton.ac.uk/mailman/listinfo/eprints-tech
