### ISSUE TITLE
MSMTP mail

### ISSUE THREAD

**Issue by gillangit** [eprints/eprints3.4#110]
anyone can help me for setting mail using smtp?

**Comment by drn05r** [comment]
This should be fairly straightforward.  See https://wiki.eprints.org/w/Setting_up_email

I have just improved these instructions a little bit, as they were a little out of date and not very detailed.  I also added the instructions about using Postfix, as this is my preferred method.

GitHub issues is generally not intended for support advice but for reporting bugs or feature requests in the code.  Generally, https://wiki.eprints.org/ is the best first place for guidance.  If you cannot find what you are looking for there.  You can sign up to the EPrints Tech mailing list at: http://mailman.ecs.soton.ac.uk/mailman/listinfo/eprints-tech and ask people on that list.
