### ISSUE TITLE
displaying http//repoURL/eprintsID fails for enabled login_required_for*

### ISSUE THREAD

**Issue by Pfiffikus** [eprints/eprints3.4#116]
The redirection of http//repoURL/eprintsID for a login_required repository leads (after successful login) to a 404 error page.
After disabling this feature in user_login.pl the redirection works ...

**Comment by drn05r** [comment]
I think this is due to a lack of code for this force login feature if you are using long URLs (i.e. /id/eprint/123 rather than /123).  It should also be noted that you need to uncomment the login_required_url config option even though it is the standard login path of "/cgi/users/login".
