### ISSUE TITLE
Embargo discrepancies between editor notices, abstract pages and the lift_embargos script

### ISSUE THREAD

**Issue by dgc** [eprints/eprints3.4#127]
There is confusion with embargo dates between the period where the embargo remains verses the period where the embargo is lifted. Notices given to the editor, information provided on the abstract page and the actual lifting of embargoes are all in conflict with each other.

  * The notices given to the editor suggest that the embargo date is always the last period where the embargo is still in effect.

  * The information given on the abstract pages suggest that (in my interpretation at least) the embargo date is always the first period where the embargo is to be lifted.

  * The `lift_embargos` script is a mixed case. When only year or year/month is specified then the embargo date is the last period where the embargo is still in effect. When year/month/day is specified then the embargo date is the first period where the embargo is to be lifted.

I performed the tests below on 2021-02-25.

| Embargo date | Editor notice | Abstract page | Lift Embargo script action |
|:---|:---|:---|:---|
| 2020 | "Embargo expiry date must be in the future." | "Restricted to Repository staff only until 2020" | Embargo lifted |
| 2021 | "Embargo expiry date must be in the future." | "Restricted to Repository staff only until 2021" | No action |
| 2022 | No message | "Restricted to Repository staff only until 2022" | No action |
| 2021-01 | "Embargo expiry date must be in the future." | "Restricted to Repository staff only until January 2021" | Embargo lifted |
| 2021-02 | "Embargo expiry date must be in the future." | "Restricted to Repository staff only until February 2021" | No action |
| 2021-03 | No message | "Restricted to Repository staff only until March 2021" | No action |
| 2021-02-24 | "Embargo expiry date must be in the future." | "Restricted to Repository staff only until 24 February 2021" | Embargo lifted |
| 2021-02-25 | "Embargo expiry date must be in the future." | "Restricted to Repository staff only until 25 February 2021" | Embargo lifted |
| 2021-02-26 | No message | "Restricted to Repository staff only until 26 February 2021" | No action |

**Comment by drn05r** [comment]
I don't see any logic of not setting a full year, month and day for an embargo.  As it is clearly important when this expires so why would you want to be vague and allow for ambiguity.
