### ISSUE TITLE
add verbosity to EPrints::Utils::get_input{,_hidden}

### ISSUE THREAD

**Issue by Pfiffikus** [eprints/eprints3.4#131]
Both subs does _not_ explain, why it is a `Bad input` ...
The user gets no idea, which regular expression the input should be!

BTW: Both subs could be merged by introducing a control for ReadMode!?

**Comment by drn05r** [comment]
My plan is to add REGEXP variables (e.g. REGEXP_ANY) to EPrints::Utils as static class variables.  These can then be referred to by epadmin.  It also means these can be used by the get_input and get_input_hidden to test which regular expression has not been matched.

**Comment by drn05r** [comment]
Fixed by 4510bd04353a637af2b47e08804a65e654ef8bbd
