### ISSUE TITLE
REST subject endpoint handles "." character in a subject identifier incorrectly

### ISSUE THREAD

**Issue by benheartland** [eprints/eprints3.4#138]
When parsing the REST request URL, [this line](https://github.com/eprints/eprints3.4/blob/5c618e327c85b6f8aed91d8708149b7544a8e6fe/perl_lib/EPrints/Apache/REST.pm#L134
):
```
my( $item_id, $format) = split( /\./, $file, 2 );
```
splits the filename on the first "." character rather than the last so, for example, the request:
`GET https://example.eprints.edu/rest/subject/item_id.still_the_item_id.xml`
would produce
```
$item_id = 'item_id'
$format = 'still_the_item_id.xml'
```
which fails with a 404 error.

To ensure splitting on the last "." character, that line should be changed to:
```
my( $item_id, $format) = split( /\.(?=[^.]+$)/, $file, 2 );
```

**Comment by drn05r** [comment]
Really the issue here is that there was/is not sufficient validation to ensure that a subject ID does not contain a full stop when it is created.  I guess the horse has bolted when it comes to managing that issue.  So I will look into making this fix.

**Comment by benheartland** [comment]
Thanks! FYI, there may be other issues with certain characters in item IDs. We had a case where the subject endpoint returned a 404 because of a "/" character in the subject ID. That case was easily fixed by removing the offending character but in general I guess that validation should be catching characters that aren't allowed in URLs and/or they should be URL encoded in API URLs.
