### ISSUE TITLE
Prevent (once) live eprint items from being removed

### ISSUE THREAD

**Issue by drn05r** [eprints/eprints3.4#145]
Once an item is live it should not be removable (only retireable).  If you remove an item that have been live even if it has previously been retired it can effect third-party application trying to sync metadata user OAI-PMH.  It may also have impact on other aspects of EPrints, especially involving export.

It maybe should still be possible to remove (once) live items but this should be very difficult. E.g. require a permission that even admin users do not have by default.  Also when an admin with this advanced permission tries to remove an item (once) live they should receive a much more strict warning about the consequences of removing such an item.

**Comment by jesusbagpuss** [comment]
I think an additional priv that works alongside existing ones might be best, as it could be re-used in:
- `EPrints::Plugin::Screen::EPrint::Remove`
- `EPrints::Plugin::Screen::EPrint::RemoveWithEmail`

The `EPrints::Plugin::Screen::EPrint::RequestRemoval` screen could also be updated to indicate that an item may be removed _or_ moved to deletion.

**Comment by drn05r** [comment]
RequestRemoval already includes in its intro "Please note that we strongly discourage removal of items from the repository".   So I don't think there is a need to add anything further to this page.

**Comment by drn05r** [comment]
I think my latest commit meets the requirements discussed. I have added info about the new permission being required to explain why "Destroy Item" will not be an option for some items on the review page, if they have previously been live.  However, I cannot think of anywhere appropriate to make repository admins more generally aware of this and how they might re-enable such a permission.  I can already imagine frantic emails on the tech list saying: "I cannot remove item X that has confidential information in it."
