### ISSUE TITLE
Accepted request-a-copy is broken if a user is logged-in

### ISSUE THREAD

**Issue by jesusbagpuss** [eprints/eprints3.4#147]
When a request-a-copy is accepted for a restricted document, the 'code' based link for the requester to access the document doesn't work if the requester is signed into their account (which doesn't have 'user'-based access to the document).

This is caused by:
1. The `user` based access is checked before the `request` based access https://github.com/eprints/eprints3.4/blob/e868bba7921ce3d35cb807d0fd32d9ca6a4c69ee/perl_lib/EPrints/DataObj/Document.pm#L2317-L2328
2. The code-based access is only in the `can_request_view_document` function, so doesn't get called when a user is logged-in. (https://github.com/eprints/eprints3.4/blob/6d2274c9ae7af5417d8ebaed609c2029ad83cd74/lib/cfg.d/security.pl#L23-L50 or https://github.com/eprints/eprints3.4/blob/6d2274c9ae7af5417d8ebaed609c2029ad83cd74/flavours/pub_lib/cfg.d/security.pl#L24-L50)

Proposed resolution: move code-based document access to a separate function; call this from both `can_request_view_document` and `can_user_view_document`.

NB I'm unsure whether this: https://github.com/eprints/eprints3.4/blob/e868bba7921ce3d35cb807d0fd32d9ca6a4c69ee/perl_lib/EPrints/DataObj/Document.pm#L1348-L1369 is active code anywhere? It seems to reproduce some of the `permit` reckoning.

**Comment by drn05r** [comment]
I have definitely already done something to fix an issue like this.  I thought it was pushed to core but maybe I only implemented on the local configuration for a particular repository.  I will look through and see if I can find this.

It also feels like this issue might have come about as a result of fixing another issue with request a copy permissions that has now introduced this new edge case bug.  I will look at the recent changes I have made to the above files.

**Comment by jesusbagpuss** [comment]
Worth noting - I've experinced this in 3.3.
I've reviewed the code in 3.4, and all the 'moving parts' appear the same - hence the Issue.

As the issue sounds familiar, it might be worth checking that it is definitely is still broken in 3.4.x.

**Comment by drn05r** [comment]
Thanks for letting me know that.  I will test before assuming it is broken.

I know I addressed this or a similar issue quite recently.  I think it was by ensuring that the request authorisation is tested first and if this fails it still continues to user authentication to see if that works.  Rather than the other way round where if user auth fails it assumes access is not permitted without testing request auth.

**Comment by drn05r** [comment]
See https://github.com/eprints/eprints3.4/commit/1b6789e7ef4299c84cd85305ae5c217a9f9eb285#diff-56d92fb323a515158cf68318f44b17a64d89f49999cb349642ef2ea49227eb05

Basically, this ensures that a failed DENY user authorization check does not automatically return 0.  Instead it carries on and does a request authorization check and that will return 1 if successful and finally only return 0 after both authorization checks have failed.

**Comment by drn05r** [comment]
I have just tested this on my GitHub test box and this is working as intended and does not suffer the reported issue.
