### ISSUE TITLE
Compatibility issue with Dates, Dates, Dates from Bazaar

### ISSUE THREAD

**Issue by kennedj** [eprints/eprints3.4#149]
Have came across an issue with 3.4.3 which seems to have cropped up when the validate function was added to [/perl_lib/EPrints/MetaField/Date.pm](https://github.com/eprints/eprints3.4/blob/master/perl_lib/EPrints/MetaField/Date.pm#L505)

This Date validation runs for Dates, Dates, Dates fields, but the validate function receives an array, which it doesn't know how to handle and always returns an invalid date error

Have added something to the validate function so it just returns if it gets an array (Dates, Dates, Dates does its own validation) but I imagine there's a nicer way of dealing with it
```perl
return () if ref($value) eq "ARRAY";
```

**Comment by drn05r** [comment]
I will look into this.  I am not sure if this is something best fixed in eprints3.4 core on in the DatesDatesDates plugin.

**Comment by drn05r** [comment]
Although a fix could be applied to the Dates^3 plugin, this would only be relevant for those running 3.4.3, so it is better to fix core and issue a patch that can be made to zz_datesdatesdates.pl to fix the problem for those runing Dates^3 onn 3.4.3 without needing to patch the core code.
