### ISSUE TITLE
Mismatch in calling code and method (EPrints::Apache::Rewrite and EPrints::Update::Views)

### ISSUE THREAD

**Issue by jesusbagpuss** [eprints/eprints3.4#150]
The Apache rewrite code that deals with views:
https://github.com/eprints/eprints3.4/blob/8c18cd49c65597539bd3fe9c1c97ef05c52694f7/perl_lib/EPrints/Apache/Rewrite.pm#L780

and the receiving code:
https://github.com/eprints/eprints3.4/blob/8c18cd49c65597539bd3fe9c1c97ef05c52694f7/perl_lib/EPrints/Update/Views.pm#L207-L209

have mis-matched parameters.

The POD references the calling version of params:
https://github.com/eprints/eprints3.4/blob/8c18cd49c65597539bd3fe9c1c97ef05c52694f7/perl_lib/EPrints/Update/Views.pm#L194

This may just be some legacy code, but thought worth reporting.

**Comment by drn05r** [comment]
Thanks John.  I don't remember changing anything that would have added or removed $localpath as a parameter.  However, I will dig a bit deeper to see if I can understand how this came about.

**Comment by jesusbagpuss** [comment]
Should have noted that this is present in 3.3 too - it's not a recent issue - and I don't think it actually breaks anything.

The View do show an unexpected behaviour. If a view has already been generated e.g /view/year/2021.html, adding extra cruft on to the end of the URL e.g. https://example.com/view/year/2021.html/some/other/nonsense/test.html responds with the 2021.html page, rather than a 404.

I'm just tracing this behaviour through the 3.3 branch - will let you now what I discover.

**Comment by drn05r** [comment]
Certainly very weird but not as yet concerning of overly problematic.  I guess we need to figure out where having a $localpath set would actually be useful.

**Comment by drn05r** [comment]
Looking on files.eprints.org, this seems to have happened between 3.2 (3.2.9) and 3.3 (3.3.5).  The old function for update_view_file was a lot longer than the one used in 3.2:

	sub update_view_file
	{
		my( $session, $langid, $localpath, $uri ) = @_;
	
		my $repository = $session->get_repository;
	
		$localpath = abbr_path( $localpath );
	
		my $target = $repository->get_conf( "htdocs_path" )."/".$langid.$localpath;
		my $ext = "";
		# remove extension from target, if there is one
		if( $target =~ s/(\.[^\.]*)$// ) { $ext = $1; }
		my $age;
		if( -e "$target.page" ) 
		{
			my $target_timestamp = EPrints::Utils::mtime( "$target.page" );
	
			$age = time - $target_timestamp;
	
			my $timestampfile = $repository->get_conf( "variables_path" )."/views.timestamp";	
			if( -e $timestampfile )
			{
				my $poketime = (stat( $timestampfile ))[9];
				# if the poktime is more recent than the file then make it look like the 
				# file does not exist (forcing it to regenerate)
				$age = undef if( $target_timestamp < $poketime );
			}		
		}
	
		if( $uri eq "/view/" )
		{
			# This should really be updated by hand, but updating it once
			# a day shouldn't hurt.
			if( defined $age && $age < 24*60*60 )
			{
				return "$target$ext";
			}
			my $file = update_browse_view_list( $session, $langid );
			return undef if( !defined $file );
			return $file.$ext;
		}
		
		$uri =~ m/^\/view(\/(([^\/]+)(\/(.*))?)?)?$/;
	
		my( $x, $y, $viewid, $z, $viewinfo ) = ( $1,$2,$3,$4,$5 );
	
		my $view;
		foreach my $a_view ( @{$repository->get_conf( "browse_views" )} )
		{
			$view = $a_view if( $a_view->{id} eq $viewid );
		}
		if( !defined $view ) 
		{
			EPrints::abort( "view with ID '$viewid' is not available." );
		}
	
		my $max_menu_age = $view->{max_menu_age} || 24*60*60;
		my $max_list_age = $view->{max_list_age} || 24*60*60;
	
		if( !EPrints::Utils::is_set( $viewinfo ) || $viewinfo =~ s/^index[^\/]+$// )
		{
			if( defined $age && $age < $max_menu_age )
			{
				return "$target$ext";
			}
	
			my $file = update_view_menu( $session, $view, $langid, [] );
			return undef if( !defined $file );
			return $file.$ext;
		}
	
		if( $viewinfo =~ s/\/$// || $viewinfo =~ s/\/index[^\/]+$// )
		{
			if( defined $age && $age < $max_menu_age )
			{
				return "$target$ext";
			}
	
			# if it ends with "/" then it's a submenu
			my @view_path = split( '/', $viewinfo );
			
			my $file = update_view_menu( $session, $view, $langid, \@view_path );
			return undef if( !defined $file );
			return $file.$ext;
		}
	
		# Otherwise it's (probably) a view list
	
		if( defined $age && $age < $max_list_age )
		{
			return "$target$ext";
		}
	
		my @view_path = split( '/', $viewinfo );
		my $file = update_view_list( $session, $view, $langid, \@view_path );
		return undef if( !defined $file );
		return $file.$ext;
	}

**Comment by drn05r** [comment]
I have checked over how this is called from Apache::Rewrite calls this function and I cannot see anyway how $localpath and $uri can have different values.  I even tried with a path (e.g. http://eprints.example.org/path/) and at the point this function is called the two values are the same.  This would explain why in the whole history of 3.3 and 3.4 no one has picked up on a problem related to this.

You report of being able to add a random path after 2021.html (as long as it end with *.html) is unrelated to this anomaly.  As already suggested although being able to do this is a bit odd, it does not give you anything different to if you had not added a random path.

**Comment by drn05r** [comment]
Ah, somehow I failed to spot that the index pages (i.e. /view/, /view/year/, etc.) have different values for $localpath and $uri.  My new conclusion is that localpath should be the variable passed and so therefore have updated the variable name for EPrints::Update::Views::update_view_file to $localpath from $uri, so this is consistent and avoid and future confusion.
