### ISSUE TITLE
get_labelledby returns wrong value if non-compound field defined as multiple=1, input_ordered=0

### ISSUE THREAD

**Issue by alex-ball** [eprints/eprints3.4#156]
In our repository, we have a non-compound field that is defined as being multiple but not ordered. This peculiar edge case outwits `get_labelledby`, which returns the `id` for the row number that `input_ordered=0` eliminates.

In the interests of making EPrints robust against the weird things we throw at it, the following fix seems to work:

```perl
sub get_labelledby
{
	my ( $self, $basename ) = @_;

	my $basename_top = $basename;
	$basename_top =~ s/_\d+_/_/
	  if $self->{multiple}
	  || ( defined $self->{parent} && $self->{parent}->{multiple} );
	$basename_top =~ s/_\d+$// if $self->{multiple} && !$self->{input_ordered};  # Fix added here
	return $basename_top . "_label";
}
```

**Comment by drn05r** [comment]
As I have said and you have already gathered, due to the different format of the help ID for different types of field and even different configuration for the same type of field, it has been tricky to be confident the aria-labelledby and aria-describedby will be applied correctly in all scenarios.  I will try to emulate your edge case to confirm this modified version of the get_labelledby function works as intended.

**Comment by alex-ball** [comment]
Don't get me wrong, I am very grateful for you getting it to work so well to begin with. Kudos!

One of the nice things about open source is having more eyeballs on the code to catch these sort of sneaky bugs.

**Comment by drn05r** [comment]
Yes.  More eyeballs is very much appreciated.  Sometimes I look back after a release and kick myself for a particular bug I missed.  However, all you can do is learn from the experience and reduce the chances missing bugs in future.  

I have a decent Jenkins installation up and running now to run daily builds.  I just need to build up the testing it carries out, as it is currently only the units tests and Selenium based testing of public-facing pages.  However, it would be impossible to check all edge cases like the one here.  So really more eyeballs is the only way to pick these up.
