### ISSUE TITLE
Can't upload file

### ISSUE THREAD

**Issue by syaifulrmdhn** [eprints/eprints3.4#162]
I can't upload file with this error` Request for https://dev-repository.nurulfikri.ac.id/cgi/users/ajax/upload_progress?progressid=B512E92491A54378A594A5B1D8F8BBD8 failed: 404 Not Found`,. How can solve it?

**Comment by drn05r** [comment]
Please take a look at previous advice given for a similar issue:

http://mailman.ecs.soton.ac.uk/pipermail/eprints-tech/2021-May/008593.html
