### ISSUE TITLE
Email metafield validation

### ISSUE THREAD

**Issue by jesusbagpuss** [eprints/eprints3.4#172]
The current validation checks for an email field allow a mis-typed address such as `someone@yahoo,com` (comma instead of dot) through.

https://github.com/eprints/eprints3.4/blob/6d2274c9ae7af5417d8ebaed609c2029ad83cd74/flavours/pub_lib/cfg.d/field_validate.pl#L85-L90

There is a regex listed on this page: https://www.w3.org/TR/2012/WD-html-markup-20120329/input.email.html to match a single email address, but there is at least one instance where the email field should support multiple email addresses (`EPrints::Plugin::Screen::Admin::TestEmail`).

IMO the Email metafield should set the input field type to 'email' - to allow for native browser validation of the input, as well as server-side validation.

**Comment by drn05r** [comment]
@jesusbagpuss It would be useful if you could check over my commit to fix this.  I have done some fairly thorough testing.  I think there may be a bit of overkill, such as not assuming that the $c->{adminemail} may not be valid and therefore should be checked.  Also perl_lib/EPrints/Plugins/Screen/Request/Respond.pm should not need to check email addresses, as it should not have been able to get that far if email addresses were invalid.

**Comment by drn05r** [comment]
Actually it does not work on account creation.  Presumably because the form does not set email address as a MetaField::Email.
