### ISSUE TITLE
Allow epadmin reindex to specify range of items

### ISSUE THREAD

**Issue by drn05r** [eprints/eprints3.4#177]
Sometimes it is useful to be able to specify a range of items to reindex rather than having to either reindex all items or specify each on individually.

**Comment by drn05r** [comment]
Implement sending ID ranges for all epadmin calls that already allow individual IDs to be specified for the particular task.

**Comment by photomedia** [comment]
I think this might not be working?  I just tried it out, and the repository didn't reindex anything when I specified range.

**Comment by photomedia** [comment]
This is working, for the record, the command looks something like this:
`epadmin reindex ARCHIVE_NAME eprint 1-10 --verbose`
Note, no square brackets around the range or IDs!
