### ISSUE TITLE
Investigate hardcoded localhost for database on "epadmin create"

### ISSUE THREAD

**Issue by drn05r** [eprints/eprints3.4#182]
The following lines hardcode **localhost**.  It is not clear why these cannot use the **dbhost** setting which should default to localhost but can be set differently:
https://github.com/eprints/eprints3.4/blob/4c1df9812d77ad98f1893483a3577cc1c2030d7b/perl_lib/EPrints/Database/mysql.pm#L144-L146

**Comment by jesusbagpuss** [comment]
> It is not clear why these cannot use the dbhost setting
I think you'd need to use a `hostname` call - to get the name of the server that EPrints is running on, rather that `dbhost` - where the DB is running?

**Comment by drn05r** [comment]
Yes, this is true.  Based on past experience this is easier said than done as sometimes the hostname you would get from a local `hostname -f` call may not be the same as what the remote database server identifies the server as been called when it tries to authenticate.  However, a hostname call is a good first bet.  So maybe set that as the default.

However, as I said in https://github.com/eprints/eprints/issues/518 it is unlikely that the EPrints server will have a current username and password they can use to authenticate with the remote database server so it can then create the new user/pass to be used for the EPrints database.

**Comment by drn05r** [comment]
The best plan would be to use the DB super username and password to create a session and then do `SELECT CURRENT_USER();` to get the username@hostname and extract the hostname for use in the two lines above instead of localhost.
