### ISSUE TITLE
Allow creators to have a single name in the required field

### ISSUE THREAD

**Issue by fatchild** [eprints/eprints3.4#185]
Creators with a single name are forced to enter both a family name and a given name. Else, a warning is shown;

> **Name in field Creators is missing the "family" part.**

**Comment by drn05r** [comment]
Actually, not requiring a given name is easily configurable, I just forgot where the validation was configured, which is: 
https://github.com/eprints/eprints3.4/blob/e5c8edc9a584ec59aa289f16a35ce1cd8f275496/flavours/pub_lib/cfg.d/field_validate.pl#L73-80

This can be copied to the local archive and modified to remove this block or add a conditional line to get it to be ignored for certain fields and not others.
