### ISSUE TITLE
Add monitoring for login attempts for better intrusion detection

### ISSUE THREAD

**Issue by drn05r** [eprints/eprints3.4#199]
Currently EPrints has no specific way for tracking login attempts beyond log lines in the webserver access log files.  This contains minimal information and makes it difficult to determine patterns and potential mitigations that should be taken.

Having a LoginAttempt data object would allow this information to store.  It should store as much information as possible to allow retrospective analysis.  It should be careful how it logs the password in login attempts.  At present the plan is to only store the password length only and only to do this on unsuccessful login attempts.  This should minimise security risks if the data for login attempts was somehow compromised.

**Comment by drn05r** [comment]
This should now be complete.  It also now logs the difference between login failing due to user with username not existing and password for user be incorrect.

**Comment by prazetyo** [comment]
Can you give me clue where we can see the log files? thank you.

**Comment by prazetyo** [comment]
Hi,

When my username and password not correct, I get this error : 
EPrints System Error
Attempt to get value from not existent field: user/unlocktime
[https://ibb.co/PQ1mfmJ](url)

thank you.

**Comment by drn05r** [comment]
Log files will appear under the archive's var/ directory in a sub-directory called login_attempts.  They will be arranged hierarchically so today's log file would be at:

EPRINTS_PATH/archives/ARCHIVEID/var/login_attempts/2022/03/22.csv

The log file is attended to be loadable as a CSV.  To make it easier to analyse for repeated attempts by the same username, user agent string or IP address over the course of the same day.

You will need to be running at least EPrints 3.4.3 to be able to patch your EPrints repository with this code, as unlocktime was only added for user in https://github.com/eprints/eprints3.4/issues/95

**Comment by prazetyo** [comment]
> Log files will appear under the archive's var/ directory in a sub-directory called login_attempts. They will be arranged hierarchically so today's log file would be at:
> 
> EPRINTS_PATH/archives/ARCHIVEID/var/login_attempts/2022/03/22.csv
> 
> The log file is attended to be loadable as a CSV. To make it easier to analyse for repeated attempts by the same username, user agent string or IP address over the course of the same day.
> 
> You will need to be running at least EPrints 3.4.3 to be able to patch your EPrints repository with this code, as unlocktime was only added for user in #95

So if I use eprints 3.4.0, this can not work? Or I just edit like #95 ?

**Comment by drn05r** [comment]
Yes, 3.4.0 is too early a version.  I would generally advise picking and choosing patches to apply to an "in production" version of EPrints.  As I cannot be certain that #95 does not rely on some post 3.4.0 changes being required.  

If you do apply #95, be sure to apply the main patch of: https://github.com/eprints/eprints3.4/commit/8079ca4a6813cbfb1af7d40713f2636072644b12 but also the subsequent patch of: https://github.com/eprints/eprints3.4/commit/23133e20fb9faae68b3af2ea16d84e3cb72415d0, which ensures the correct date/time format is saved to unlocktime, if the account gets locked. 

I would also consider applying the patch: https://github.com/eprints/eprints3.4/commit/93395c260060b567de52d0c7962bb4c41fe5f7b6 as although this only changes the documentation within a comment, it may make things easier if/when you upgrade to a later version of EPrints.

**Comment by drn05r** [comment]
You could just comment out the bit about unlocktime.  Although this would also make things messier when it comes to an upgrade.  However, if you want to do this it would be to comment out the following block:

```
if ( defined $user && $user->get_value( "unlocktime" ) )
{
    my $unlocktime = $repo->make_text( EPrints::Time::human_time( $user->get_value( "unlocktime" ) ) );
    $processor->add_message( "error", $repo->html_phrase( "cgi/login:locked", unlocktime=>$unlocktime ) );
    $self->{processor}->{logged_login} = EPrints::Plugin::Screen::Login::log_login_attempt( $repo, $username, $password, 'locked' );
    EPrints::Plugin::Screen::Login::log_login_attempt( $repo, $username, $password, 'locked' );
}
```

And to change the following line from:		
```elsif( defined $user )```

to just 
```if( defined $user )```

If you do apply #95 be sure to run the following to add the new unlocktime field to user:

> EPRINTS_PATH/bin/epadmin update ARCHIVEID

**Comment by prazetyo** [comment]
> Log files will appear under the archive's var/ directory in a sub-directory called login_attempts. They will be arranged hierarchically so today's log file would be at:
> 
> EPRINTS_PATH/archives/ARCHIVEID/var/login_attempts/2022/03/22.csv
> 
> The log file is attended to be loadable as a CSV. To make it easier to analyse for repeated attempts by the same username, user agent string or IP address over the course of the same day.
> 
> You will need to be running at least EPrints 3.4.3 to be able to patch your EPrints repository with this code, as unlocktime was only added for user in #95

I already success using this locktime, but the folder login_attempts still not created.
fyi, I already patch with 8079ca4 .

Thank you

**Comment by prazetyo** [comment]
This is my folder archives/ARCHIVEID
> eprints@repo16-04:~/archives/ArchiveID$ ls -l
total 28
drwxrwsr-x  3 eprints eprints 4096 Feb 17  2019 bin
drwxrwxr-x 11 eprints eprints 4096 Dec 30  2020 cfg
drwxrwxr-x  4 eprints eprints 4096 May 14  2019 cgi
drwxrwxr-x  3 eprints eprints 4096 Apr 25  2014 documents
drwxrwxr-x  3 eprints eprints 4096 Apr 25  2014 html
drwxrwxr-x  2 eprints eprints 4096 Feb  3 19:05 ssl
drwxrwxr-x  5 eprints eprints 4096 Jul  1  2016 var

But for user running, still www-data. is it the cause of problem??

> ...
www-data  2171  0.1  0.8 369104 124360 ?       S    19:51   0:00 /usr/sbin/apache2 -k start
www-data  2175  0.0  0.8 361036 116776 ?       S    19:51   0:00 /usr/sbin/apache2 -k start
www-data  2176  0.0  0.8 361036 116776 ?       S    19:51   0:00 /usr/sbin/apache2 -k start
www-data  2182  0.1  0.8 373280 123464 ?       S    19:51   0:00 /usr/sbin/apache2 -k start
www-data  2183  0.1  0.8 369156 123364 ?       S    19:51   0:00 /usr/sbin/apache2 -k start
www-data  2187  0.0  0.8 361036 116776 ?       S    19:51   0:00 /usr/sbin/apache2 -k start
www-data  2188  0.0  0.8 361036 116776 ?       S    19:51   0:00 /usr/sbin/apache2 -k start
www-data  2189  0.3  0.8 369104 124064 ?       S    19:51   0:00 /usr/sbin/apache2 -k start
www-data  2302  0.0  0.8 361020 116776 ?       S    19:52   0:00 /usr/sbin/apache2 -k start
www-data  2303  0.3  0.8 369140 122992 ?       S    19:52   0:00 /usr/sbin/apache2 -k start
www-data  2304  0.3  0.8 369140 122992 ?       S    19:52   0:00 /usr/sbin/apache2 -k start
www-data  2325  0.0  0.7 360992 114644 ?       S    19:52   0:00 /usr/sbin/apache2 -k start
www-data  2327  0.0  0.7 360992 114644 ?       S    19:52   0:00 /usr/sbin/apache2 -k start
www-data  2328  0.0  0.7 360992 114644 ?       S    19:52   0:00 /usr/sbin/apache2 -k start
eprints   2330  0.0  0.0  14220   940 pts/2    R+   19:52   0:00 grep \(httpd\|apache\)

**Comment by drn05r** [comment]
That will be your issue.  I would advise adding the www-data user to the eprints group, also set the Set GID bit for the var directory (substitute EPRINTS_PATH and ARCHIVEID appropriately):

usermod -a -G eprints www-data
chmod 2775 EPRINTS_PATH/archives/ARCHIVEID/var

**Comment by prazetyo** [comment]
> ps aux | grep '\(httpd\|apache\)'

I already change user:group to eprints

> eprints   4494  0.0  0.8 360240 116056 ?       S    20:36   0:00 /usr/sbin/apache2 -k start
eprints   4495  0.0  0.8 360240 116056 ?       S    20:36   0:00 /usr/sbin/apache2 -k start
eprints   4499  0.0  0.8 360240 116056 ?       S    20:36   0:00 /usr/sbin/apache2 -k start
eprints   4500  0.0  0.8 360240 116064 ?       S    20:36   0:00 /usr/sbin/apache2 -k start
eprints   4501  0.2  0.8 368820 123972 ?       S    20:36   0:00 /usr/sbin/apache2 -k start
eprints   4503  0.0  0.8 360240 116056 ?       S    20:36   0:00 /usr/sbin/apache2 -k start
eprints   4506  0.3  0.8 368696 123992 ?       S    20:36   0:00 /usr/sbin/apache2 -k start
eprints   4508  0.0  0.8 360240 116056 ?       S    20:37   0:00 /usr/sbin/apache2 -k start
eprints   4510  0.3  0.8 368344 122004 ?       S    20:37   0:00 /usr/sbin/apache2 -k start
eprints   4511  1.1  0.8 368644 123860 ?       S    20:37   0:00 /usr/sbin/apache2 -k start
eprints   4513  0.0  0.0  14220   936 pts/8    S+   20:37   0:00 grep \(httpd\|apache\)

I also change usermod and chmod. But the folder login_attempts still can not created.

**Comment by drn05r** [comment]
I am at a loss.  I would check the Apache error log files to see if  this tell you anything useful.

Other than that, I would wait until EPrints 3.4.4 and upgrade.  As there may be some issue due to patching in only certain parts of the new code since 3.4.0, which creates an issue, which does not generate any error output.  It is difficult for me to help debug this problem when I cannot have an equivalent setup to test, as the code is not consistent with a particular version of even Git changeset of EPrints 3.4.

**Comment by prazetyo** [comment]
> I am at a loss. I would check the Apache error log files to see if this tell you anything useful.
> 
> Other than that, I would wait until EPrints 3.4.4 and upgrade. As there may be some issue due to patching in only certain parts of the new code since 3.4.0, which creates an issue, which does not generate any error output. It is difficult for me to help debug this problem when I cannot have an equivalent setup to test, as the code is not consistent with a particular version of even Git changeset of EPrints 3.4.

Hi,

Thank you David for your guide. I think you're right, it maybe because my eprints version still 3.4.0. But, the lock time is running well, even it doesn't create a csv file.
