### ISSUE TITLE
cal bugs

### ISSUE THREAD

**Issue by Cook879** [eprints/eprints3.4#211]
Three changes I've made on a site, that should probably apply back to core

1) cgi/cal no longer accepts the param r=flow

proposed to add an exception to the value check of 
`$_ eq "r" && $session->param( $_ ) eq "flow"`
alternatively could update the regex to check letters and numbers

2) CSS rule `#d$today` doesn't work

I think `#$today` should match the current ID style, but I just added the `background-color: #ccccff;` to the `.today` class

3) The `cal` command on Ubuntu 20.04 adds in some extra chars to highlight today (_ followed by a backspace, twice) to the calendar on the screen.

To get a clean version of the calendar on Ubuntu, need to run `ncal -b -h $_mon $_y |` instead of `cal $_mon $_y |`

My local change used `lsb_release -si` to get the os name and decide whether to run ncal or cal based on that, but given centos doesn't seems to not have lsb_release installed, there's probably a better way?

**Comment by drn05r** [comment]
Please submit a pull request and after review I will merge this into master.
