### ISSUE TITLE
 $sys->sanitise( $filepath ) assumes we are in CGI mode

### ISSUE THREAD

**Issue by cgutteridge** [eprints/eprints3.4#213]
$sys->sanitise( $filepath ) fails if you call it from the command line because it creates a new EPrints object and assumes "current_repository" is set.

A partial work around would be to change the line from  

         if ( $repo->can_call( "optional_filename_sanitise" ) )

to

        if ( defined $repo && $repo->can_call( "optional_filename_sanitise" ) )

However really if it has repository-specific behaviour the method should belong to Repository but that might be hard to do.

**Comment by drn05r** [comment]
I'll take a look. Have you got a use case so I can test once I have fixed this?

**Comment by cgutteridge** [comment]
(I'm going to cheat for today and override the script)

**Comment by drn05r** [comment]
Hmm.  Surprised that has not caused me an issue up to now.  I have CI running and this flagged an issue and I have been doing regular development on HEAD of the master branch and not seen anything.
