### ISSUE TITLE
Codespell report for "EPrints" (on fossies.org)

### ISSUE THREAD

**Issue by jschleus** [eprints/eprints3.4#225]
The FOSS server [fossies.org](https://fossies.org) - supporting also the [EPrints](https://fossies.org/eprints) project - offers among others a feature named "[Source code misspelling reports](https://fossies.org/features.html#codespell)". Such reports are normally only generated on request, but as Fossies administrator I have just created for testing purposes such a [codespell](https://github.com/codespell-project/codespell) based analysis for the "EPrints" release 3.4.3:

&nbsp;https://fossies.org/linux/www/eprints/codespell.html

That version-independent URL should redirect always to the last report (if available), so currently to

&nbsp;https://fossies.org/linux/www/eprints3.4-3.4.3.tar.gz/codespell.html

A further report was generated for the new release candidate 3.4.4-rc1:

&nbsp;https://fossies.org/linux/www/eprints3.4-3.4.4-rc1.tar.gz/codespell.html

By the way, the context type of the spelling errors and typos are marked by a single character (within the sortable column "T"): The less interesting, probably not user visible ones (in "comments") are greyed, while the probably more interesting ones are black-colored. Especially interesting may be unassigned errors marked by a "?" since they may be contained in the source code itself. Some more according information is offered by a tooltip if the mouse is over the string "error context type character" above the table, over the "T" in the table header or over such a context character itself within the table. If JavaScript is enabled all table columns are sortable.

Although after a first review some obviously wrong matches ("False Positives" = FPs) are already filtered out (ignored) please inform me if you find more of them so that I can force a new improved check if applicable.

Just for information there are also three supplemental pages showing some used "codespell" [configuration details](https://fossies.org/linux/wwweprints/codespell_conf.html), all obvious [false positives](https://fossies.org/linux/www/eprints/codespell_fps.html) and an [misspelling history](https://fossies.org/linux/www/eprints/codespell_hist.html) (log).

Perhaps more meaningful may be a similar and continuously updated report for the EPrints GitHub "master" version which is available within a special restricted "test" folder that isn't really integrated into the standard Fossies services and should also not be accessible to search engines:

&nbsp;https://fossies.org/linux/test/eprints-eprints3.4-master-snap.tar.gz/codespell.html

That version independent URL hopefully always redirects to the report for the latest "master" version identified by the short commit ID and a year-month-day string (YYMMDD) representing the according git pull date (mostly = commit date). The refresh rate is at least currently every half hour.

OK, spelling corrections certainly have a low priority, but they may also contribute to the overall quality of a software project. So I hope that the report can nevertheless be a little bit useful.

**Comment by drn05r** [comment]
Fossies.org have run a codespell analysis report on the latest GitHub HEAD.  The only word they found typos for was 'theses'.  I explained this was just the plural of thesis, which is commonly used terminology used within EPrints, so they updated their analysis report dictionary to allow this.

**Comment by jschleus** [comment]
Ok, a bit nitpicking: A new codespell run found in the file `debian/postinst.in` at line number 46 the word `isses` what probably is a typo and should be `issues`.

**Comment by drn05r** [comment]
Fixed in https://github.com/eprints/eprints3.4/commit/a05139930e6872f531cc5c482f28301d57c16a97
