### ISSUE TITLE
Exports: byte_order_mark not used from web interface

### ISSUE THREAD

**Issue by jesusbagpuss** [eprints/eprints3.4#229]
**Should web exported data include a BOM for certain formats?**

From my code analysis, some files exported on the commandline will include a BOM, but no web-invoked exports will.
Is this a design decision or oversight? Tracing it back through EPrints3.3, it appears to have worked this way since for _a long time_.

For some formats e.g. MultilineCSV, including a BOM will make the file more usable for some people (Windows+Excel users).

One fix could be to add support for an 'include_bom' parameter to `cgi/export`:
```perl
    $plugin->initialise_fh( \*STDOUT );
    if( $repository->param( "include_bom" ) )
    {
        print $plugin->byte_order_mark;
    }
```
which would mean existing integrations with exported data would continue to work, but there would be a pathway to generate a file with a BOM if the export format defines one.

### The reasoning
The Export plugin defines a `byte_order_mark` method which by default is an empty string:
https://github.com/eprints/eprints3.4/blob/afa570c12a967422e916b64b55fde9d57ea2566a/perl_lib/EPrints/Plugin/Export.pm#L400-L403

The `EPrints::Plugin::Export::TextFile` class redefines this (NB See list below of export plugins that subclass `TextFile`):
https://github.com/eprints/eprints3.4/blob/6f83a78eb738fbd88b3816fc97ffecaf43bf811d/perl_lib/EPrints/Plugin/Export/TextFile.pm#L30-L35

The only place I can see this method being called is the commandline export:
https://github.com/eprints/eprints3.4/blob/cfc8dc27c001cfbbc08f32d6fa363b1b99a9093d/bin/export#L232

Adding either

#### Export plugins that subclass `EPrints::Plugin::Export::TextFile`
JSON
RDF
Simple
BadData
COinS
FlatSubjects
Text
DC
EndNote

**Comment by drn05r** [comment]
I don't see a problem adding this, as you say it would only cause different behaviour if an explicit parameter is set.  I see that there are five functions in cgi/export that have the line:
> $plugin->initialise_fh( \*STDOUT );

Which of the following are you referring to or do all of them need updating:

1. export_eprints
2. export_rdf_dump
3. export_rdf_repository
4. export_subject
5. export_rdf_resource

**Comment by jesusbagpuss** [comment]
Good question - I'm just looking through these to work out what the right option is.
I think the RDF ones should be OK as-is, but just researching that...

There may be some export plugins e.g. MultilineCSV that would also need to have a byte_order_mark method added.

**Comment by jesusbagpuss** [comment]
I think it probably needs adding to both CRUD and the direct cgi/export script?

Looking at the [Apache Rewrite hander](https://github.com/eprints/eprints3.4/blob/cfc8dc27c001cfbbc08f32d6fa363b1b99a9093d/perl_lib/EPrints/Apache/Rewrite.pm#L171-L284) the CRUD module isn't involved with serving cgi scripts?

**Comment by jesusbagpuss** [comment]
I've traced the code through - and can now see you're right... sorry.

The 'export_eprints' sub in cgi/export gets invoked from a url of:  `/cgi/export/records` 

The CRUD interface does get invoked in most cases.

As the RDF export formats inherit from TextFile (which defines a BOM), I think the safest approach is to have a specific URL param to govern this.
