### ISSUE TITLE
site_lib plugins are read in additionally

### ISSUE THREAD

**Issue by Pfiffikus** [eprints/eprints3.4#23]
the (sometimes additional) reading of extending plugins in https://github.com/eprints/eprints3.4/blob/fabcf978b3dcc7e07ce443ef82d68c2dd9eb7f1d/perl_lib/EPrints/PluginFactory.pm#L104-L110 is inconsistent to the introduction of the flavour ranking (read in afterwards), i.e. the new filesystem structure without explicitly mentioned `./site_lib`.

Should the aforementioned lines removed?

**Comment by drn05r** [comment]
Yes.  You are correct site_lib should be included under the inc file in the flavour (e.g EPRINTS_PATH/flavours/pub_lib/inc) so explicitly including it in PluginFactory is not just unnecessary but forces an ordering when we want this to be flexible based on the inc file.

I will look into fixing PluginFactory.pm and testing to make sure behaviour does not change.

**Comment by drn05r** [comment]
Actually behaviour might change but at least there will be confidence in the ordering and if necessary inc files can be reordered.  Most people will not be using site_lib out of the box, so it likely to have limited impact.
