### ISSUE TITLE
Ancestor subjects in browse show same number of items as one random child

### ISSUE THREAD

**Issue by alex-ball** [eprints/eprints3.4#253]
In our (Zero-flavoured) repository, we find that ancestor subjects in browse menus show the same number of items as one random child, e.g.

- Faculty of Engineering & Design (72)
    - Architecture and Civil Engineering (100)
    - Chemical Engineering (72)
    - Electronic & Electrical Engineering (38)
    - Mechanical Engineering (102)

I think I can explain what is going on here. In `EPrints::Update::Views::fieldlist_sizes()` the relevant bit is:

https://github.com/eprints/eprints3.4/blob/e5e071ed369ea712f6cdecebc35a3b9b9ed0b4d3/perl_lib/EPrints/Update/Views.pm#L2248-L2268

Say we have terms `fac1`, `dept1`, `dept2` and `$id_map` is something like
```perl
{ dept1 => [1, 2, 3], dept2 => [4, 5] }
```

Then on one iteration we get:
```perl
%cur_subj_map = ( dept1 => { 1 => 1, 2 => 1, 3 => 1 }, fac1 => { 1 => 1, 2 => 1, 3 => 1 } );
```

and on the other iteration we get:
```perl
%cur_subj_map = ( dept2 => { 4 => 1, 5 => 1 }, fac1 => { 4 => 1, 5 => 1 } );
```

What I gather is happening in our case is that when we get to
```perl
%subj_map = ( %subj_map, %cur_subj_map ) if $subj_found;
```
we end up with one of the `fac1` values overwriting the other, depending on the order in which the `$id_map` keys are processed, e.g.
```perl
%subj_map = ( dept1 => { 1 => 1, 2 => 1, 3 => 1 }, dept2 => { 4 => 1, 5 => 1 }, fac1 => { 4 => 1, 5 => 1 } );
```

In our case we can solve this by writing to `%subj_map` directly when iterating, instead of using the intermediate `%cur_subj_map` – after all, the `$id_map` is already filtered so it seems a relatively small saving to filter again at this point, and we're not affected by #181 – but for a general solution I think a deeper merge function is needed here.

**Comment by hmirlohi** [comment]
Thanks a lot. I also had the same problem and this solution solved it.
