### ISSUE TITLE
Upgrade eprints 3.2.9 to 3.4

### ISSUE THREAD

**Issue by asnanmtakim** [eprints/eprints3.4#267]
How can i upgrade eprints from 3.2.9 to latest 3.4?
Is there a manual for it?
Thanks you.

**Comment by drn05r** [comment]
You will need to upgrade from 3.2.9 to 3.3 and then 3.3 to the latest 3.4.  The EPrints wiki has instructions for this:

https://wiki.eprints.org/w/Upgrading_from_3.2
https://wiki.eprints.org/w/Upgrading_3.3.12%2B_to_3.4
