### ISSUE TITLE
desirable option 'prune' for generate_views

### ISSUE THREAD

**Issue by Pfiffikus** [eprints/eprints3.4#271]
As stray files occur also for views, I would appreciate the same option as in generate_static.

**Comment by drn05r** [comment]
This would not be as straightforward as `generate_static` as they checks for a file in the various static directories and if it does not exist in any of them, it warns that the file might need to be pruned (and prunes if `--prune` flag is set).

There are two levels for this.  One is removing a view that is no longer configured.  This is fairly straightforward, as you just get all the view IDs and a listing of all the sub-directories under `html/<LANG>/view/` and then just those in the latter that are not in the former.

Deleting indvidual view listing pages would be more difficult and it is questionable whether if you only use `--generate menus` whether these should be pruned if a `--prune` flag was also set.  To remove individual view listing pages would require a function to enumerate all the expected pages to compare against those that actually exist to determine which ones to prune.

**Comment by drn05r** [comment]
For deleting individual view listing and menu pages, I think it is best to just delete those older than the maximum permitted cache.  Worse case scenario this will delete pages that are still active but would be overwritten next time they were requested because their cache had expired.
