### ISSUE TITLE
BibTex cannot successfully import phdthesis out of the box

### ISSUE THREAD

**Issue by fatchild** [eprints/eprints3.4#272]
The BibTex import plugin tries to set @phdthesis as thesis_type "phd", which does not exist as standard (Some repos have added it locally).

`flavours/pub_lib/cfg.d/eprint_fields_pub.pl`
```perl
{
        name => 'thesis_type',
        options => [qw(
                diploma
                masters
                doctoral
                postdoctoral
                other
        )],
},

{
        name => 'thesis_name',
        options => [qw(
                mphil
                phd
                dphil
                other
        )],
},
```

`flavours/pub_lib/plugins/EPrints/Plugin/Import/BibTeX.pm`
```perl
if( $type eq "MASTERSTHESIS" )
{
	$epdata->{type} = "thesis";
	$epdata->{thesis_type} = "masters";
}
if( $type eq "PHDTHESIS" )
{
	$epdata->{type} = "thesis";
	$epdata->{thesis_type} = "phd";
}
```

BibTex export assumes anything other than a masters is a phd type, which reduces thesis_type to 2 options from the 5 in EPrints3.4 (diploma, masters, doctoral, postdoctoral, other). But that is in line with https://www.bibtex.com/format/ .

`flavours/pub_lib/plugins/EPrints/Plugin/Export/BibTeX.pm`
```perl
if( $type eq "thesis")
{
	if( $dataobj->exists_and_set( "thesis_type" ) && $dataobj->get_value( "thesis_type" ) eq "masters" )
	{
		$data->{type} = "mastersthesis";
	}
	else
	{
		$data->{type} = "phdthesis";	
	}
}
```

### Possible solution;
- Map "phdthesis" to the "doctoral" option of thesis_type within the Import and then export module will automatically assume doctoral as phdthesis. 

`flavours/pub_lib/plugins/EPrints/Plugin/Import/BibTeX.pm`
```perl
if( $type eq "PHDTHESIS" )
{
	$epdata->{type} = "thesis";
	$epdata->{thesis_type} = "doctoral";
}
```

**Comment by drn05r** [comment]
I would suggest also still add `$epdata->{thesis_name} = "phd";` as we know the this is an available option and theoretically a **PHDTHESIS** could not be any of the other thesis name options.
