### ISSUE TITLE
Overarching setting for maximum file upload size

### ISSUE THREAD

**Issue by drn05r** [eprints/eprints3.4#286]
Suggested by @jesusbagpuss:

Could be a config option e.g. `$c->{apache}->{LimitRequestBody} = 2147483648;`

This could then be used in both the Apache config and perl modules/javascript.

**Comment by drn05r** [comment]
I think is would be best to just call the configuration setting `$c->{max_upload_filesize}` but with a comment above about where it is used.

**Comment by jesusbagpuss** [comment]
Ideally:
- the comment should mention 'LimitRequestBody'
- the fragment added to the Apache vhost should reference the file/config option `$c->{max_upload_filesize}`
