### ISSUE TITLE
Staff search should be able to find eprints without metadata_visibility = 'show'

### ISSUE THREAD

**Issue by drn05r** [eprints/eprints3.4#299]
If you try to find an eprint using staff search (Search Items in Admin menu) then you won't be able to find it even if you search in its specific eprintid if it does not have `metadata_visibility = 'show'`.  

Staff search should be able to find all items as admins may need to make amendments to older versions of eprints that have been succeeded.

**Comment by Ainmhidh** [comment]
Either ignore the metadata_visibility where the search criteria includes an eprintid or, as drn05r suggested on the tech-list, have a checkbox to ignore hide status in admin search.

**Comment by drn05r** [comment]
@Ainmhidh The main issue is that the metadata_visibility = 'show' looks quite baked into the search API.  Maybe when I look a little deeper there is a nice flag to tell the search API to ignore metadata_visibility.  Obvioulsy, care needs to be taken to make sure that metadata_visibility restriction for public search is not broken by any changes.

**Comment by yurj** [comment]
Are there any other use of metadata_visibility? I mean, other eprints that have it on `hide` other than older versions.

**Comment by drn05r** [comment]
@yurj So the `metadata_visibility` can be one of three values: `hide`, `show` or `no_search`.  I think in your old version situation the item will have had `metadata_visibility` set to `no_search`.  There are not any other scenarios in the codebase that I can see where `metadata_visibility` is modified to something other than `show`.  However, I think bespoke additions may have made use of this as well as third party applications, I know Symplectic Elements heavily used  versioning for EPrints' Repository Tools 1 (RT1) plugin.  

I have to admit that scenarios where you want to hide the metadata but still be able to access the abstract page would be rare.  As metadata_visibility does not modify robots.txt or say anything on the abstract page to stop Google and its like indexing such abstract pages.

**Comment by yurj** [comment]
I've implemented your suggestion in `cgi/search`:

```perl
if( $dataset->base_id eq "eprint" && $searchid ne "staff" )
{
        push @filters,
                { meta_fields => ["metadata_visibility"], value => "show" };
}
```
