### ISSUE TITLE
CRUD interface GET request for non-existent EPrints returns FORBIDDEN rather than NOT_FOUND when a user is present

### ISSUE THREAD

**Issue by jesusbagpuss** [eprints/eprints3.4#309]
Apologies - long-winded title, long-winded explanation. There is a short proposed fix though ;)

To reproduce (assuming you don't have in Eprint with ID 999999999999999 in your repo):
```
GET /id/eprint/999999999999999
Headers:
'Accept' => 'application/vnd.eprints.data+xml'
'Authorization' => 'Basic [a valid basic auth string]'
```
Returns: `403 Forbidden`
Expected return: `404 Not found`

The 403 is returned by the `$crud->authz` method.

The request is handled by this code in `EPrints::Apache::Rewrite`:
https://github.com/eprints/eprints3.4/blob/ff35468439c93951325881bdd06c280a57b2df60/perl_lib/EPrints/Apache/Rewrite.pm#L584-L606
setting `authn`, `authz` and `handler` on the Apache request handler stacks.

As the request being made contains an Authorization header, the `authn` returns OK, and the flow passes to `authz`
https://github.com/eprints/eprints3.4/blob/ff35468439c93951325881bdd06c280a57b2df60/perl_lib/EPrints/Apache/CRUD.pm#L890-L912
The first 'if' here doesn't match, as the EPrint doesn't exist.
The second test `elsif( defined $user )` is entered (as there is a user), but they may not be allowed to do $priv (eprint/export in this case)
The last 'else' isn't hit, as the above `elsif` was entered.
The `return HTTP_FORBIDDEN` is reached.

NB The CRUD API _does_ allow for an eprint with a specific ID to be created (so a `POST /id/eprint/999999999999999` should create an EPrint with that ID (if config allows).
I think this is the reason a '404' has not been generated by the time the above code is reached.

One solution would be to add the following:
```perl
if( defined $dataobj )
{
	... # current code
}
elsif( $self->method eq "GET" || $self->method eq "HEAD" )
{
	# no dataobject so return a 404
	return HTTP_NOT_FOUND;
}
elsif( defined $user )
{
# continues as existing code
```
although I'm not sure this is the best place to generate the 404.

NB Not sure if an 'OPTIONS' request should also be handled in the above. I'm not sure what an OPTIONS request should return for a non-existant item...

**Comment by drn05r** [comment]
Your suggestion looks like a sensible and neat solution. Although I don't know if `PUT`, `PATCH` and `DELETE` should also be added.  I shall investigate that, as maybe those are handled elsewhere.

I cannot imagine `OPTIONS` requests are made very often.  They don't return any data just requests types (e.g. `GET`, `HEAD`, etc.) that can be made.  If a data object does not exist, saying theoretically what options would be allowed I don't think is a real issue.  As soon as they tried one of these options, they would be informed the data object does not exist using your suggested solution.

**Comment by jesusbagpuss** [comment]
I think `PUT` and `PATCH` should be handled by other aspects of the CRUD code (user privs - possibly on the dataobj).
An item _not_ existing doesn't preclude a user (with sufficient privs) creating an item with that ID - so a `PUT` / `PATCH` shouldn't return a 404 (I think... I tried to follow all this through!).

**Comment by drn05r** [comment]
I have just reviewed this and I think some code like the following will work better:

```
elsif ( defined $self->{dataobjid} )
{
   return HTTP_NOT_FOUND;
}
```

**Comment by jesusbagpuss** [comment]
I think that the above, combined with the `GET` / `HEAD` aspect might be the best - given that EPrints supports an 'upsert' type function.
With _just_ the above, coming before the `$user` checks, a PUT/POST won't/can't create a dataobj with the ID provided.
