### ISSUE TITLE
Redundant code in EPrints::Extras

### ISSUE THREAD

**Issue by jesusbagpuss** [eprints/eprints3.4#313]
This block of code appears to be redundant:
https://github.com/eprints/eprints3.4/blob/c53b3522023e1ec8e3eb2d8fdc7d8ffb328f300c/perl_lib/EPrints/Extras.pm#L59-L62

I think it's left over from the LibXML / DOM days, as a similar set of options appears in `EPrints::XML::DOM::parse_xml_string`, but not the LibXML equivalent.

**Comment by drn05r** [comment]
Seems reasonable to tidy this up.  I will looking into modifying this file.
