### ISSUE TITLE
import sets <datestamp> even for --update

### ISSUE THREAD

**Issue by Pfiffikus** [eprints/eprints3.4#32]
this modification is somehow harmless, but confusing on the summary page, because it's _not_ the date of deposition for this history

**Comment by drn05r** [comment]
Datestamp is set for an imported item with archive eprint_status if the the --update flag is not used.  This is correct behaviour even if the datestamp is already set in the imported EP3XML, as this is a new item and the date this item was deposited is when you ran the import command, if the eprint_status is already set to 'archive'.

When I use the --update flag is sent, the existing record is updated this does not modify the datestamp field only the lastmod date field.
