### ISSUE TITLE
on 'manage records' screen some undefined phrases arose

### ISSUE THREAD

**Issue by Pfiffikus** [eprints/eprints3.4#34]
error log:
`Undefined phrase: eprint:workflow:stage:core:title (en) at line 168 in /usr/share/eprints/perl_lib/EPrints/Workflow/Stage.pm
Undefined phrase: eprint:workflow:stage:files:title (en) at line 168 in /usr/share/eprints/perl_lib/EPrints/Workflow/Stage.pm
Undefined phrase: eprint:workflow:stage:subjects:title (en) at line 168 in /usr/share/eprints/perl_lib/EPrints/Workflow/Stage.pm
Undefined phrase: eprint:workflow:stage:type:title (en) at line 168 in /usr/share/eprints/perl_lib/EPrints/Workflow/Stage.pm
Undefined phrase: file_fieldname_copies (en) at line 423 in /usr/share/eprints/perl_lib/EPrints/MetaField.pm
Undefined phrase: file_fieldname_copies_pluginid (en) at line 423 in /usr/share/eprints/perl_lib/EPrints/MetaField.pm
Undefined phrase: file_fieldname_copies_sourceid (en) at line 423 in /usr/share/eprints/perl_lib/EPrints/MetaField.pm
Undefined phrase: file_fieldname_data (en) at line 423 in /usr/share/eprints/perl_lib/EPrints/MetaField.pm
Undefined phrase: file_fieldname_url (en) at line 423 in /usr/share/eprints/perl_lib/EPrints/MetaField.pm
Undefined phrase: subject_fieldname_sortvalue (en) at line 423 in /usr/share/eprints/perl_lib/EPrints/MetaField.pm
Undefined phrase: subject_fieldname_sortvalue_lang (en) at line 423 in /usr/share/eprints/perl_lib/EPrints/MetaField.pm
Undefined phrase: subject_fieldname_sortvalue_sortvalue (en) at line 423 in /usr/share/eprints/perl_lib/EPrints/MetaField.pm
Undefined phrase: user_fieldname_pin (en) at line 423 in /usr/share/eprints/perl_lib/EPrints/MetaField.pm
Undefined phrase: user_fieldname_pinsettime (en) at line 423 in /usr/share/eprints/perl_lib/EPrints/MetaField.pm`

**Comment by drn05r** [comment]
This looks in part a case of mapping the equivalent archive:workflow:stage:*:title to eprint:workflow:stage:*:title
  
Otherwise this looks like various overlooked fields for different data objects.  So this is just a case of going through and adding the phrases.  I think some of the user fields are never used by default but would be in manage records as they are defined fields.
