### ISSUE TITLE
Making public user emails by default is probably not the best default

### ISSUE THREAD

**Issue by photomedia** [eprints/eprints3.4#344]
I would remove this default which makes public depositor/author emails in the ATOM export.

https://github.com/eprints/eprints3.4/blob/47267178056eba3950d9ed3116c6c8650455ce5c/perl_lib/EPrints/Plugin/Export/Atom.pm#L356

**Comment by drn05r** [comment]
This needs some review as other plugins are liable to behave similar.  Ideally there needs to be a binary config option to allow showing emails to be switched on or off across all places they may be publicly accessible.

**Comment by photomedia** [comment]
Agreed, we have done this type of review in the past, so we have these visible to staff only:
#TN : to avoid exporting out email addresses
$c->{plugins}->{"Export::JSON"}->{params}->{visible} = "staff";
$c->{plugins}->{"Export::XML"}->{params}->{visible} = "staff";
$c->{plugins}->{"Export::RDFN3"}->{params}->{visible} = "staff";
$c->{plugins}->{"Export::RDFNT"}->{params}->{visible} = "staff";
$c->{plugins}->{"Export::RDFXML"}->{params}->{visible} = "staff";
$c->{plugins}->{"Export::CSV"}->{params}->{visible} = "staff";
$c->{plugins}->{"Export::Simple"}->{params}->{visible} = "staff";
The Atom export must have changed during the recent upgrade from 3.3 to 3.4, so I just noticed it recently.  In general, I think that by default, EPrints should not export out to public email addresses of depositors and authors.
