### ISSUE TITLE
Documentation inconsistent on preferred way to install

### ISSUE THREAD

**Issue by alex-ball** [eprints/eprints3.4#346]
I see from the comment below that deb and rpm builds have been discontinued as a policy decision, but this is not reflected on the wiki.

> Unfortunately, we no longer do deb or rpm builds for EPrints as we have found that as EPrints has quite complex dependencies including those that cannot be satisfied by the package managers.  For some time we have recommended that these packages (deb and rpm) only be used for demo purposes.

_Originally posted by @drn05r in https://github.com/eprints/eprints3.4/issues/337#issuecomment-1740837605_

The [main installation guide](https://wiki.eprints.org/w/Installation) describes installing from a tarball on a generic Linux distribution, but the reader is recommended instead to follow the instructions for [installing on Red Hat](https://wiki.eprints.org/w/Installing_EPrints_on_RHEL/Fedora/CentOS) or [installing on Debian](https://wiki.eprints.org/w/Installing_EPrints_on_Debian/Ubuntu).

Both of those sets of instructions describe installing from pre-built packages (rpm, deb) as the first option. They also contain the emphatic warning, "**Installing from source is generally discouraged particularly for production repositories,**" before describing installing via `git`.

But on the page on [upgrading](https://wiki.eprints.org/w/Upgrading) it is mentioned that the preferred installation option for production repositories is the `git` method of installing from source. Even there, upgrading by package manager is still given as the first option despite this not working for systems where 3.4.4 is installed.

Please could you

- on the main installation page, add instructions on installing via `git`;
- on the Red Hat and Debian pages, remove the warning about installing from source, promoting it to the preferred method, and either deprecate or remove the instructions for installing from pre-built packages instead;
- on the upgrade page, remove the instructions on upgrading via Package Manager, since this no longer works.

This would help avoid a great deal of confusion.

**Comment by drn05r** [comment]
Yes, I plan to update those when I get a chance.

**Comment by drn05r** [comment]
Updated instructions at the following wiki packages to remove instructions for installing using a package and explaining the reasoning:

- https://wiki.eprints.org/w/Installing_EPrints_on_Debian/Ubuntu
- https://wiki.eprints.org/w/Installing_EPrints_on_RHEL/Fedora/CentOS
