### ISSUE TITLE
ERR_TOO_MANY_REDIRECTS on browse pages

### ISSUE THREAD

**Issue by oawebdev** [eprints/eprints3.4#350]
Hello! 
After some time of normal working system I've got an error of TOO_MANY_REDIRECTS on the pages like /view/year/, /view/divisions, /view/*, /eprints. Other pages works well.
Browser tries to add/remove / at the end of url and fails. 
Was v3.3, now upgraded to v3.4 and the problem still exist.

FreeBSD 12.4
Perl v5.32.1
Apache/2.4.58
ap24-mod_perl2-2.0.12

**Comment by drn05r** [comment]
It would be useful to know what URLs are being redirected between,  If you could run wget or curl from the command and provide the URLs it loops through.  I suspect it will just be redirecting something like A->B->A... ir A->B->C->A.  It may be that their is a flipping between HTTP and HTTPS but more likely there will be an issue with URLs that do and don't have a trailing /.

It would also be useful to know any configuration in 10_core.pl, 20_base_urls.pl and any config files that set things like:

1. `$c->{base_url}`
2. `$c->{http_url}`
3. `$c->{https_url}`
4. `$c->{rel_path}`
5. `$c->{http_root}`
6. `$c->{https_root}`

Also, please can you confirm with version of EPrints 3.4 you are now trying to run and whether this issue was already present when you were running 3.3 or this has only occurred since upgrading to 3.4.

**Comment by oawebdev** [comment]
Thank you for the fast reply.

> It would be useful to know what URLs are being redirected between, If you could run wget or curl from the command and provide the URLs it loops through. I suspect it will just be redirecting something like A->B->A... or A->B->C->A. It may be that there is a flipping between HTTP and HTTPS but more likely there will be an issue with URLs that do and don't have a trailing /.

Website url is https://eprints.oa.edu.ua/
```
wget https://eprints.oa.edu.ua/view/year
--2023-11-07 01:54:18--  https://eprints.oa.edu.ua/view/year
Resolving eprints.oa.edu.ua (eprints.oa.edu.ua)... 192.168.5.3
Connecting to eprints.oa.edu.ua (eprints.oa.edu.ua)|192.168.5.3|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: /view/year/ [following]
--2023-11-07 01:54:18--  https://eprints.oa.edu.ua/view/year/
Reusing existing connection to eprints.oa.edu.ua:443.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: https://eprints.oa.edu.ua/view/year [following]
--2023-11-07 01:54:18--  https://eprints.oa.edu.ua/view/year
Reusing existing connection to eprints.oa.edu.ua:443.
HTTP request sent, awaiting response... 302 Found
Location: /view/year/ [following]
--2023-11-07 01:54:18--  https://eprints.oa.edu.ua/view/year/
Reusing existing connection to eprints.oa.edu.ua:443.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: https://eprints.oa.edu.ua/view/year [following]
--2023-11-07 01:54:18--  https://eprints.oa.edu.ua/view/year
Reusing existing connection to eprints.oa.edu.ua:443.
HTTP request sent, awaiting response... 302 Found
Location: /view/year/ [following]
--2023-11-07 01:54:18--  https://eprints.oa.edu.ua/view/year/
Reusing existing connection to eprints.oa.edu.ua:443.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: https://eprints.oa.edu.ua/view/year [following]
--2023-11-07 01:54:18--  https://eprints.oa.edu.ua/view/year
Reusing existing connection to eprints.oa.edu.ua:443.
HTTP request sent, awaiting response... 302 Found
Location: /view/year/ [following]
--2023-11-07 01:54:18--  https://eprints.oa.edu.ua/view/year/
Reusing existing connection to eprints.oa.edu.ua:443.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: https://eprints.oa.edu.ua/view/year [following]
--2023-11-07 01:54:18--  https://eprints.oa.edu.ua/view/year
Reusing existing connection to eprints.oa.edu.ua:443.
HTTP request sent, awaiting response... 302 Found
Location: /view/year/ [following]
--2023-11-07 01:54:18--  https://eprints.oa.edu.ua/view/year/
Reusing existing connection to eprints.oa.edu.ua:443.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: https://eprints.oa.edu.ua/view/year [following]
--2023-11-07 01:54:18--  https://eprints.oa.edu.ua/view/year
Reusing existing connection to eprints.oa.edu.ua:443.
HTTP request sent, awaiting response... 302 Found
Location: /view/year/ [following]
--2023-11-07 01:54:18--  https://eprints.oa.edu.ua/view/year/
Reusing existing connection to eprints.oa.edu.ua:443.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: https://eprints.oa.edu.ua/view/year [following]
--2023-11-07 01:54:18--  https://eprints.oa.edu.ua/view/year
Reusing existing connection to eprints.oa.edu.ua:443.
HTTP request sent, awaiting response... 302 Found
Location: /view/year/ [following]
--2023-11-07 01:54:18--  https://eprints.oa.edu.ua/view/year/
Reusing existing connection to eprints.oa.edu.ua:443.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: https://eprints.oa.edu.ua/view/year [following]
--2023-11-07 01:54:18--  https://eprints.oa.edu.ua/view/year
Reusing existing connection to eprints.oa.edu.ua:443.
HTTP request sent, awaiting response... 302 Found
Location: /view/year/ [following]
--2023-11-07 01:54:18--  https://eprints.oa.edu.ua/view/year/
Reusing existing connection to eprints.oa.edu.ua:443.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: https://eprints.oa.edu.ua/view/year [following]
--2023-11-07 01:54:18--  https://eprints.oa.edu.ua/view/year
Reusing existing connection to eprints.oa.edu.ua:443.
HTTP request sent, awaiting response... 302 Found
Location: /view/year/ [following]
--2023-11-07 01:54:18--  https://eprints.oa.edu.ua/view/year/
Reusing existing connection to eprints.oa.edu.ua:443.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: https://eprints.oa.edu.ua/view/year [following]
--2023-11-07 01:54:18--  https://eprints.oa.edu.ua/view/year
Reusing existing connection to eprints.oa.edu.ua:443.
HTTP request sent, awaiting response... 302 Found
Location: /view/year/ [following]
--2023-11-07 01:54:18--  https://eprints.oa.edu.ua/view/year/
Reusing existing connection to eprints.oa.edu.ua:443.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: https://eprints.oa.edu.ua/view/year [following]
--2023-11-07 01:54:18--  https://eprints.oa.edu.ua/view/year
Reusing existing connection to eprints.oa.edu.ua:443.
HTTP request sent, awaiting response... 302 Found
Location: /view/year/ [following]
20 redirections exceeded.
```
```
>curl https://eprints.oa.edu.ua/view/year/
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>301 Moved Permanently</title>
</head><body>
<h1>Moved Permanently</h1>
<p>The document has moved <a href="https://eprints.oa.edu.ua/view/year">here</a>.</p>
</body></html>
```

> It would also be useful to know any configuration in 10_core.pl, 20_base_urls.pl and any config files that set things like:
10_core.pl
```
$c->{host} = 'eprints.oa.edu.ua';
$c->{port} = 80;
$c->{aliases} = [
                  {
                    'redirect' => 'yes',
                    'name' => 'www.eprints.oa.edu.ua'
                  },
                  {
                    'redirect' => 'yes',
                    'name' => 'eprints'
                  }
                ];
$c->{http_url} = 'https://eprints.oa.edu.ua';
$c->{http_cgiurl} = 'https://eprints.oa.edu.ua/cgi';
$c->{base_url} = "https://$c->{host}";
$c->{securehost} = $c->{host};
$c->{secureport} = 443;
$c->{http_root} = undef;
```

20_base_urls.pl
```
# These configuration variables are mostly unused and should be deprecated.

{
	my $uri = URI->new( "http://" );
        if( EPrints::Utils::is_set( $c->{securehost} ) )
        {
                $uri->scheme( "https" );
                $uri->host( $c->{securehost} );
                $uri->port( $c->{secureport} );
                $uri = $uri->canonical;
                $uri->path( $c->{https_root} );
        }
        else
        {
                $uri->scheme( "http" );
                $uri->host( $c->{host} );
                $uri->port( $c->{port} );
                $uri = $uri->canonical;
                $uri->path( $c->{http_root} );
        }

# EPrints base URL without trailing slash
	$c->{base_url} = "$uri";
# CGI base URL without trailing slash
	$c->{perl_url} = "$uri/cgi";
# Uncomment to keep URI for eprint items as http or different to base_url.
# May need editing, if repository on unusual port number, not on the root path or host is unset because HTTPS everywhere is configured.
	#$c->{uri_url} = "http://" . $c->{host};
}

# If you don't want EPrints to respond to a specific URL add it to the
# exceptions here. Each exception is matched against the uri using regexp:
#  e.g. /myspecial/cgi
# Will match http://yourrepo/myspecial/cgi
#$c->{rewrite_exceptions} = [];

#Set EPrints abstract page url to /id/eprint/XX instead of the shorter version /XX, for search engine optimisation.
$c->{use_long_url_format} = 1; 
```

> Also, please can you confirm with version of EPrints 3.4 you are now trying to run and whether this issue was already present when you were running 3.3 or this has only occurred since upgrading to 3.4.
The issue starts in 3.3 two weeks ago. Before it works fine.

**Comment by candrawardana** [comment]
same problem here, but when login, v. 3.4.5

**Comment by drn05r** [comment]
I cannot see how infinite redirects would have started happening without a code or configuration change.  However, this could be a very subtle change that you might not have noticed or even just running a script (e.g. generate_apacheconf) that replaces cached configuration.  The Apache configuration you have listed under apache_ssl has to be included by another file.  It would be useful if you could provide the configuration of this file.  Typically this will be stored under the archive, typically as ssl/securevhost.conf.  However, there is nothing stopping you putting it elsewhere.  A good way to track it down is to run one of the following command (depending on your Linux OS):

**Comment by drn05r** [comment]
On a working 3.4.5 repository if you request /view/year you will be redirected to /view/year/ and this page will load without further redirects.  If you request /view/year/ this will load without any redirects.  I think there must be some configuration that has changed on your webserver.  I cannot be sure what but mod_dir most closely relates to your issue:

- https://httpd.apache.org/docs/2.4/mod/mod_dir.html

**Comment by oawebdev** [comment]
> I cannot see how infinite redirects would have started happening without a code or configuration change. However, this could be a very subtle change that you might not have noticed or even just running a script (e.g. generate_apacheconf) that replaces cached configuration. The Apache configuration you have listed under apache_ssl has to be included by another file. It would be useful if you could provide the configuration of this file. Typically this will be stored under the archive, typically as ssl/securevhost.conf. However, there is nothing stopping you putting it elsewhere. A good way to track it down is to run one of the following commands (depending on your Linux OS) as the root user:
> 
> `source /etc/apache2/envvars && apache -S`
> 
> `httpd -S`

```
<VirtualHost *:443>

    ServerName eprints.oa.edu.ua:443

    # Enable HSTS
    Header always set Strict-Transport-Security "max-age=63072000;"

    SSLEngine on
    SSLProtocol all -SSLv2 -SSLv3
    SSLHonorCipherOrder on
    SSLCipherSuite HIGH:!aNULL:!eNULL:!kECDH:!aDH:!RC4:!3DES:!CAMELLIA:!MD5:!PSK:!SRP:!KRB5:@STRENGTH

    SSLCertificateFile .../letsencrypt/live/eprints.oa.edu.ua/fullchain.pem
    SSLCertificateKeyFile .../letsencrypt/live/eprints.oa.edu.ua/privkey.pem
    SSLCertificateChainFile .../letsencrypt/live/eprints.oa.edu.ua/fullchain.pem

    SetEnvIf User-Agent ".*MSIE.*" \
        nokeepalive ssl-unclean-shutdown \
        downgrade-1.0 force-response-1.0

    LogLevel warn
    #ErrorLog logs/ssl_error_log    
   # TransferLog logs/ssl_access_log
    #CustomLog logs/ssl_request_log \
        "%t %h %{SSL_PROTOCOL}x %{SSL_CIPHER}x \"%r\" %b"

    Include .../eprints3/cfg/apache_ssl/oa.conf

    PerlTransHandler +EPrints::Apache::Rewrite

</VirtualHost>
```

**Comment by drn05r** [comment]
Sorry, I never got back to you.  After the latest information you provided, I had run out of ideas of what might have been causing your redirects problem.  Looking back to the wget output you gave me, I would expect the `302 Found` redirects from `/view` to `/view/` but the `301 Moved Permanently` redirecting `/view/` to `/view`.  The only code in EPrints that does permanent redirect (301) would not affect view pages only eprint abstract/summary pages.  

Having looked through your EPrints specific Apache configuration, I cannot see anything that would cause a permanent redirect.  Therefore, I have to reckon that there is something in some other part of your Apache configuration, which does not like URLs that end in a / and tries to redirect them to a URL will the / removed.  Below are some examples of individual configuration lines that would try to remove the trailing slash.  

```
RedirectMatch ^/(.*?)/$ /$1
RewriteRule ^(.*)/$ /$1 [L,R=301]
```
Maybe one of your other sites does this for some reason and the configuration in leaked into your EPrints configuration.  Otherwise, one of these or something similar may have been added to Apache's core configuration under `/etc/apache24/`.
