### ISSUE TITLE
ISIWoK plugin - SOAP API retired

### ISSUE THREAD

**Issue by polyrobin** [eprints/eprints3.4#361]
The SOAP API for Web of Science has been retired by Clarivate https://support.clarivate.com/ScientificandAcademicResearch/s/article/Web-of-Science-SOAP-API-Sunset-Frequently-asked-questions-FAQs?language=en_US

Is there any plans to upgrade the plugin to the new REST API?

**Comment by drn05r** [comment]
I am not certain but I don't think ISIWoK API-based import is widely used within EPrints.  Therefore, there are currently no plans to rewrite this to use the REST API.  However, if someone want to rewrite this I would be happy to review a pull request and if ok merge it so it can be provided in a future release of EPrints.

I will look into removing the SOAP version of the plugin if the API has been retired.
