### ISSUE TITLE
Allow certain URL paths to be blocked for certain IPs

### ISSUE THREAD

**Issue by drn05r** [eprints/eprints3.4#388]
Some requests are processor intensive.  If a bot discovers these they can sometimes hammer them an DoS EPrints.  Blocking them outright may not be appropriate (e.g if they are Google) but blocking certain requests (e.g. /cgi/exportview/...) may be useful if certain IPs are putting a lot of load on the server.

**Comment by drn05r** [comment]
I agree that ultimately putting these is Apache is more efficient than in EPrints but the difference is relatively trivial compared to the amount of load put on the server by the request running in full.  Also the way that EPrints set up the Perl Handler, you often need to add a rewrite exceptions in EPrints Perl configuration to allow Apache to handle this (e.g. with Shibboleth), at which point if you then already hitting the application rather than just the webserver,

In a case where an IP address is hammering an EPrints repository aggressively with no due cause, then using iptables (or nftables) is probably the correct solution to minimise any impact it has on the server.

**Comment by tgoeg** [comment]
Yeah, that makes sense. Just wanted to note it down in case anyone want to find an Apache-only solution.
