### ISSUE TITLE
Error if upload files 1MB more

### ISSUE THREAD

**Issue by yc8nyj** [eprints/eprints3.4#398]
Hello....i has been install eprints 3.4.5 pub in ubuntu 22.04 , but if try upload file pdf with capacity 1MB more.... always error Request for https://repository.uwn.ac.id/cgi/users/ajax/upload_progress?progressid=78F10C3C8FA4415B8FA5E0C193B014F1 failed: 404  
please help me how to solved it?

**Comment by drn05r** [comment]
This sounds like a permissions issue.  Larger files need to use EPRINTS_PATH/tmp/ (e.g. /opt/eprints3/tmp/) as a intermediate storage path.  Make sure that Apache has permissions to write and create sub-directories under this directory.

**Comment by drn05r** [comment]
Also depending on your config it may try to use plain /tmp/, which may not have permissions to write/create sub-directories.  You can either edit session.pl and set: `$ENV{'TMPDIR'} = '/opt/eprints3/tmp/'; or make sure the user running Apache has suitable permissions on /tmp/.

**Comment by drn05r** [comment]
Assuming my answer fix the reported issue.
