### ISSUE TITLE
Event Queue - Primary Key violation

### ISSUE THREAD

**Issue by jesusbagpuss** [eprints/eprints3.4#4]
Reported on the Tech-list: http://threader.ecs.soton.ac.uk/lists/eprints_tech/thread-23483.html

```
ERROR:  duplicate key value violates unique constraint "event_queue_pkey"
DETAIL:  Key (eventqueueid)=(e9210339587b3507d2bdafc95a238a39) already exists. at /opt/eprints3/perl_lib/EPrints/Database.pm line 1387.
        EPrints::Database::add_record('EPrints::Database::Pg=HASH(0x55aa5922a478)', 'EPrints::DataSet=HASH(0x55aa57023030)', 'HASH(0x55aa592f77c8)') called at /opt/eprints3/perl_lib/EPrints/DataObj.pm line 294
```

My interpretation of this error is:
The 'eventqueueid' is generated from a hash of the parameters that will be used in the index event:
https://github.com/eprints/eprints3.4/blob/v3.4.0/perl_lib/EPrints/DataObj/EventQueue.pm#L88-L110

This means that if *exactly* the same event (e.g. generate RDF for EPrint X) is created twice, the eventqueueid will be the same, and the new task should not get added to the index queue.

The EPrints::DataObj::EventQueue::create_unique code calls EPrints::DataObj create_from_data (https://github.com/eprints/eprints3.4/blob/v3.4.0/perl_lib/EPrints/DataObj.pm#L221-L353) which then tries to add the data to the database: https://github.com/eprints/eprints3.4/blob/v3.4.0/perl_lib/EPrints/DataObj.pm#L293-L295 using EPrints::Database::add_record.

This code *is* working correctly:
https://github.com/eprints/eprints3.4/blob/v3.4.0/perl_lib/EPrints/Database.pm#L1387-L1388
An error is raised when a duplicate ID is used.
This will return '0' to the calling code, which in turn returns undef to the EventQueue call.

The question here is: which module should be responsible for checking whether the eventqueueid already exists before trying to insert it.
Most other modules use auto-increment keys, so this isn't an issue.

We could add a dataset search for the MD5 in EPrints::DataObj::EventQueue::create_unique before trying to re-create the event?

**Comment by jesusbagpuss** [comment]
@drn05r  - should this check the status of the pre-existing event?
If it's in a failed state, maybe it should reset it to 'waiting?

**Comment by drn05r** [comment]
I will consider this.  I was worried that this could lead to some sort of feedback loop where the status keeps flicking between waiting and failed.  However, I cannot think of any specific cases where that is likely to happen.

**Comment by jesusbagpuss** [comment]
I think it would be good to write something into the indexer log something like:
"Resetting event X (status was 'failed' on 2020-04-15 12:34:56)"

I can't think of anything specifically that would re-spawn events that quickly…
