### ISSUE TITLE
XML::LibXML 2.0201+ requires explicit enabling for external DTDs 

### ISSUE THREAD

**Issue by drn05r** [eprints/eprints3.4#41]
Reported by Paolo Tealdi via Eprints-tech

this version the module needs one more MANDATORY option at startup, that enables 
external DTD parsing, now disabled by default.

**Comment by jesusbagpuss** [comment]
There are a few places this might need correcting.
I'm building a list at:
https://github.com/eprints/eprints/issues/511

**Comment by drn05r** [comment]
An issues to review use of XML libraries has been add to the 3.4.3 milestone as #52
