### ISSUE TITLE
Setting a template for a screen plugin / the user area

### ISSUE THREAD

**Issue by jesusbagpuss** [eprints/eprints3.4#414]
Trying to set a template for a specific screen via plugin params doesn't work by adding e.g. the following to the archive config:
```perl
# overriding both, just to be sure!
$c->{plugins}->{"Screen::Register"}->{params}->{template} = 'default';
$c->{plugins}->{"Screen::Register::Internal"}->{params}->{template} = 'default';
```

Search pages have a slightly different handling. The search config can include a reference to a template, and this does seem to be honoured.

There's also the ability to set e.g.
`$c->{user_area_template} = 'user';`

Which the `cgi/users/home` script then passes to the screen processor: https://github.com/eprints/eprints3.4/blob/3451d147855809d92e4fbda604401e7f7223b78e/cgi/users/home#L43-L46

I think the changes around the 'default_internal' template have stopped this being honoured.

I'm not sure how setting a template for specific screens is meant to work.
It looks like a template can now be set via a search parameter - but ideally I would be able to set it for a specific screen at the repository config level, and this would trump any URL param passed in.

I think the fix for the `user_area_template` aspect is easier to fix.

**Comment by drn05r** [comment]
I think it is just a case of amending the Screen plugin so it can take the `{params}->{template}` values if they are set.  However, the prioritisation between this `user_area_template` and `template` in the GET header needs to be considered.  I think after that it should be a relatively simple fix.

**Comment by jesusbagpuss** [comment]
My preference for most screens would be to _not_ allow a URL param to govern the template.

I can see the changes around search results display, and those supporting a template might be useful, but I think this should ordinarily be internally routed, not part of a public facing URL.

**Comment by drn05r** [comment]
I think I have mainly fixed the hard-coding to default_internal by just setting `$c->{user_area_template}= 'default_internal';` rather than hard-coding this in a couple of places.  The problem is still getting it to pick up the {params}->{template} config.  At moment my precedence is:
1. GET header
2. Search config (where applicable)
3. Plugin params
4. user_area_template
I appreciate the GET header is maybe something you don't want to allow, so I will look at whether there is a config setting that could disable that (and maybe disable by default).

**Comment by drn05r** [comment]
@jesusbagpuss see 12426a98132d05b7cf1257824bcd3b212fb06a07

**Comment by jesusbagpuss** [comment]
@drn05r  - this looks spot-on :)

The config control for the GET param is a really sensible addition.

**Comment by drn05r** [comment]
OK.  Sounds like this can be closed.
