### ISSUE TITLE
History ICal export refers to ecs.soton in all entries

### ISSUE THREAD

**Issue by jesusbagpuss** [eprints/eprints3.4#42]
https://github.com/eprints/eprints3.4/blob/1dc46958229115ac8698f2e886efac4ba2ebd618/perl_lib/EPrints/Plugin/Export/HistoryICal.pm#L94

should use something like `$self->{session}->config( "host" );` (or `securehost`?)

**Comment by drn05r** [comment]
Hi John,

If you could try this changeset or apply it as a patch to test that would be useful, as it does not link into anything I can easier make use of to test it works as expected.  That said the change is rather simple, so should just work.

Thanks

David Newman

**Comment by jesusbagpuss** [comment]
Hi David,
I don't actually have a 3.4 instance running. I noticed this on our 3.3  instance  - but thought (seeing as it's not a _bad_ issue (I'd put it more at a typo level), it wasn't worth fixing in 3.3!

Cheers,
John

**Comment by drn05r** [comment]
I am not aware of any code in 3.3. or 3.4 that integrates with this plugin.  If you have some code even for 3.3, that does integrate that you could send me it would allow me to properly test my change.

**Comment by jesusbagpuss** [comment]
If you do a 'history search', there's an option to export the result set as a History iCal. I tried using this today (for the first time ever I think), which is when I spotted it...

To validate this fix, run the above, and the resultant iCal file will contain the hostname, rather than .ecs.soton... (unless you're testing on a report with a host of ecs.soton... :o)

**Comment by jesusbagpuss** [comment]
NB a visual inspection of your code looks spot-on!

**Comment by drn05r** [comment]
Obviously, history search!  I have tested and it looks good.
