### ISSUE TITLE
'toform' rendered unusable by EPrints::MetaField::Itemref->render_single_value

### ISSUE THREAD

**Issue by alex-ball** [eprints/eprints3.4#48]
In the [manual page on EPrints Metadata Fields](https://wiki.eprints.org/w/Category:EPrints_Metadata_Fields#Input_and_Validation_Properties), there is this suggestion:

**toform**: This function is allowed to modify the current value which appears in the form. For example, if your database stores userids in a field, but you want to allow people to edit them as usernames, then this function can be used to take the current value (a userid) and return the associated username.

The trouble is, if you have this in place for an `itemref` field (like, say, `user`) that appears in a workflow, the row is rendered as both the value and a citation rendered from the value.

Normally for, say, user ID 1234, username jd46:

```
[  1234  ]  John Doe
```

With **toform** in place:

```
[  jd46  ]  User jd46 not found.
```

The trouble arises because when render_single_value tries to get the object, it is using the value output by the **toform** function (username), not the value from the database (userid).

For this to work properly, presumably EPrints::MetaField::Itemref should override EPrints::MetaField->render_input_field to somehow preserve the unconverted value (as an extra parameter at then end?), or else convert it back again using the **fromform** function if it is defined.

**Comment by drn05r** [comment]
Example configuration for itemref field with which is use toform.  Required fromform and new get_item functions to be defined to do reverse mappings.  get_item get data object fromform get the id for the data object.
 
```
push @{$c->{fields}->{eprint}},
{
        name=>"myuserid",
        type=>"itemref",
        datasetid=>"user",
        required=>0,
        toform=>"myuserid_toform",
        fromform=>"myuserid_fromform",
        get_item=>"myuserid_get_item",

};

$c->{myuserid_toform} = sub
{
        my( $userid, $session ) = @_;
        my $user_ds = $session->get_repository->get_dataset( "user" );
        my $user = $user_ds->dataobj( $userid );
        return $user->get_value( 'username' ) if defined $user;
};

$c->{myuserid_get_item} = sub
{
        my( $username, $session ) = @_;
        my $user = EPrints::DataObj::User::user_with_username( $session, $username );
        return $user if defined $user;
        return undef;
};

$c->{myuserid_fromform} = sub
{
        my( $username, $session ) = @_;
        my $user = EPrints::DataObj::User::user_with_username( $session, $username );
        return $user->id if defined $user;
        return undef;
};

```

**Comment by alex-ball** [comment]
Sorry to reopen this after so long, but I recently tried this solution and there's a problem.

Workflow Details screen: `EPrints::Plugin::Screen::Workflow::Details::render` calls `$dataobj->render_value( $fieldname, 1 )` when displaying the current value of each field. This calls `$field->render_value`, and hence `$field->render_single_value`, with `$dataobj->value($fieldname)` (i.e. the database value) as the value parameter.

Workflow Edit screen: `EPrints::Metafield::render_input_field` converts the database value into the form value with the `tofrom` subroutine, and eventually calls (in this case) `EPrints::Metafield::Itemref::get_basic_input_elements`. The latter adds the label to the normal basic input element using `$field->render_single_value`, with the form value as the value parameter.

The solution you've used in this fix is to (allow the user to) override `$field->get_item` when it gets called by `$field->render_single_value`, so that it expects the form value instead of the database value. But it will still receive the database value when called by the Details screen. This means that one has the following choices:

- Have "User jd46 not found" in the Edit screen and "John Doe" on the Details screen (using default `get_item`).
- Have "John Doe" in the Edit screen and "User 1234 not found" on the Details screen (using a `get_item` sub that expects the form value).
- Write a `get_item` sub that interprets a purely numeric value as the raw database value, and all other values as form values. This would lead to unwanted results if the form value also happens to be a numerical value.

Building on what I originally suggested, one would avoid the need for a custom (and possibly dodgy) `get_item` sub if `fromform` was used by `get_basic_input_elements`, perhaps like this:

```perl
# EPrints::MetaField::Itemref
sub get_basic_input_elements
{
	my ( $self, $session, $value, $basename, $staff, $obj,
		$one_field_component )
	  = @_;

	my $ex =
	  $self->SUPER::get_basic_input_elements( $session, $value, $basename,
		$staff, $obj, $one_field_component );

	# New code
	my $raw_value = $value;
	if ( defined $value && defined $self->{fromform} )
	{
		if ( $self->get_property("multiple") )
		{
			$raw_value = pop @{
				$self->call_property( "fromform", [$value], $session, $obj,
					$basename )
			};
		}
		else
		{
			$raw_value =
			  $self->call_property( "fromform", $value, $session, $obj,
				$basename );
		}
	}
	my $desc = $self->render_single_value( $session, $raw_value );
	# End of new code

	push @{ $ex->[0] }, { el => $desc, style => "padding: 0 0.5em 0 0.5em;" };

	return $ex;
}
```

**Comment by drn05r** [comment]
That sounds reasonable.  I will have a play around with this on my dev repository and see if there are any edge cases that still need addressing.  I might also fix the hard-coded style attribute in favour of a class for CSS.

**Comment by drn05r** [comment]
For others' benefit, if they have a version of EPrints before this fix is included): The code block in my original advice could be fixed with a `get_item` function like the following or even more generically something that calls the existing `myuserid_toform` or `myuserid_fromform` depending on regex check for the type of value supplied.  E.g. 
```
$c->{myuserid_get_item} = sub
{
        my( $username, $session ) = @_;
        my $user;
        if ( $username !~ m/^\d+$/ )
        {
            $user = EPrints::DataObj::User::user_with_username( $session, $username );
        }
        else
        {
            $user = $session->get_repository->get_dataset( "user" )->dataobj( $username );
        }
        return $user if defined $user;
        return undef;
};
```
However, that is clearly a hack and may fail in cases where a username is completely numeric or other scenarios where it is impossible to make a distinction in the format of the tofrom and fromform values.  So your code change would save the need for this potentially unreliable hack and save effort on configuring the field with a `myuserid_get_item` function and assigning this to the `get_item` attribute for the field.  However, the `myuserid_tofrom` and `myuserid_fromform` functions would still be needed and assigned respectively to the `toform` and `fromform` attributes of the field.

**Comment by alex-ball** [comment]
Sorry, but another problem has been introduced.

In commit 83881eb, this block of code is removed from `EPrints::MetaField::Itemref`:

```perl
sub new
{
        my( $self, %params ) = @_;
	$params{regexp} = '' if defined $params{fromform} && ! defined $params{regexp};
       	return  $self->SUPER::new( %params );
}
```

Taking your earlier example,

```perl
push @{$c->{fields}->{eprint}},
{
        name=>"myuserid",
        type=>"itemref",
        datasetid=>"user",
        toform=>"myuserid_toform",
        fromform=>"myuserid_fromform",
        get_item=>"myuserid_get_item",
};
```

this field would therefore now implicitly get the property `regexp => qr/-?[0-9]+/` from `EPrints::MetaField::Int::get_property_defaults`.

Therefore when the form is rendered and the database integers get transformed to usernames, the next time the record is saved or the "Lookup" button is used, the value fails the regexp at `EPrints::MetaField::Int::form_value_basic` because it's a name, not an integer. Therefore the whole value is returned undefined, wiping it in the database.

To avoid complete data loss on this field, one has to set, say,  `regexp => '.*',` in the field definition.

(I can't see this parameter documented on the Wiki under [Metadata](https://wiki.eprints.org/w/Metadata), [Int](https://wiki.eprints.org/w/Int_field) or [Itemref](https://wiki.eprints.org/w/Itemref_field), so it takes a bit of detective work to find this out.)

Would it be possible to restore `EPrints::MetaField::Itemref::new` in some form so this additional configuration is not required?

**Comment by drn05r** [comment]
Sorry about that.  I think you best stopgap solution is as you said to add the regexp attribute to your field definitions.

The commit suggests that the previous regexp was wrong but I am not sure why we did not pick up the issue you reported during testing.  Like you, we probably looked at the documentation and thought: "no super class sets regexp, so lets just get rid of that line as it is easier not to have to worry about it."  However, it is clear we need to make sure a regexp is set that won't cause issues for ItemRef.

I think the documentation issue was introduced due to the default values for parameters potentially being set in two places in a Metafield class `new` and `get_property_defaults`, combined with inheritance and potential multiple instances of `field_defaults.pl` or locations of `field_defaults` configuration, often makes it difficult to ensure properties document accurately.  I will look to review this

**Comment by alex-ball** [comment]
From code inspection alone I can't see why it would make a difference, but if it helps to reproduce this issue, the field I noticed this on had `multiple => 1` set.

**Comment by drn05r** [comment]
My investigations so far seem to suggest a problem somewhere else in the code:
```
Can't use string ("") as an ARRAY ref while "strict refs" in use at /opt/eprints3/perl_lib/EPrints/MetaField.pm line 1403.
```
This only happens for a mutiple itemref field and not if it is multiple int field or a single itemref field.  This is probably due to needing to modify the `myuserid_fromform` and `myuserid_toform`  to support multiple fields.  Here is those two rewritten and they seem to fix this issue.

```
$c->{myuserid_fromform} = sub
{
        my( $usernames, $session ) = @_;
        my $userids = [];
        foreach my $username ( @$usernames ) 
        {
                my $user = EPrints::DataObj::User::user_with_username( $session, $username );
                push @$userids, $user->id if defined $user;
        }
        return $userids;
};

$c->{myuserids_toform} = sub
{
        my( $userids, $session ) = @_;
        my $user_ds = $session->get_repository->get_dataset( "user" );
        my $usernames = [];
        foreach my $userid ( @$userids )
        {
                my $user = $user_ds->dataobj( $userid );
                push @$usernames, $user->get_value( 'username' ) if defined $user;
        }
        return $usernames;
};
```

From what you previously described, I am not sure if this is the problem you have been experiencing.  Now I have reviewed the code I think the removal of the `regexp` attribute setting is correct because when an itemref value is saved to the database it should be an integer because the reference is the ID of the item.  I guess in certain chases the item's ID might not be an auto-incremented integer (like `eprintid` and `userid`) but as already discussed, at that point the field definition should be changed  to set an appropriate regexp attribute.

**Comment by alex-ball** [comment]
The `toform` and `fromform` functions will get passed the value as an arrayref on multiple fields, scalars/hashrefs on non-multiple fields, because of where it happens in the code. It would be nice if that wasn't the case (more on this below) but as I said before it's somewhat beside the point.

Here is the way the code flows on an Itemref field:

1. `$field->form_value` (MetaField) is called.
2. `$field->form_value` calls `$field->form_value_actual` (MetaField)
3. `$field->form_value_actual` calls `$field->form_value_single` (MetaField). On a multiple field, it calls it for each `${basename}_$i`; on a non-multiple field, it calls it just once for `$basename`.
4. `$field->form_value_single` calls `$field->form_value_basic` (MetaField::Int).
5. `$field->form_value_basic` (MetaField::Int) calls `$field->form_value_basic` (MetaField)
6. `$field->form_value_basic` (MetaField) gets the value from the POST parameters. It does a bit of processing and returns it. In the case in point, this has the username string.
7. `$field->form_value_basic` (MetaField::Int) then tests the value against the regexp set for the field. `MetaField::Itemref::new` set this regexp to `''`, but without that in place, the default for Itemref is the same as for MetaField::Int, i.e. `qr/-?[0-9]+/`. The username string obviously fails this, so the sub returns `undef`.
8. `$field->form_value_single` sees the returned value fails `EPrints::Utils::is_set( $value )` so returns `undef`.
9. `$field->form_value_actual`, in a non-multiple case, simply returns what it gets. In the multiple case, it checks `EPrints::Utils::is_set( $value )` again on each single value that comes back, and adds the ones that pass to an array. Since none do, the array is empty and it returns `undef`. (If it worked, a ref to the array would be returned.)
10. Finally, `$field->form_value` looks to see if the `form_value_actual` is defined. If it is, it runs the `fromform` sub on it and what comes back is the new value. The desired result here is that the username goes in (usernames in the multiple case) and the ID integer comes back on a match, or `undef` if there was no match (or an arrayref of ID integers in the multiple case - not sure if `undef` or an empty arrayref is preferable here but it looks like either works). But the `form_value_actual` is `undef` so that is what is returned.

Now, from a functional perspective the `fromform` function is doing the same work that `MetaField::Int::form_value_basic` is doing with the regexp: checking to see if it is a valid value and discarding it if not. So it would make considerable sense if `fromform` was called immediately before the test in `MetaField::Int::form_value_basic` (which as things stand would be `MetaField::form_value_basic`, but see below) instead of `MetaField::form_value`:

- It would always be passed a single value rather than an arrayref, so no need to have two different versions of (essentially) the same function depending on whether the field was multiple or not.
- In this particular case it would do the transformation before the rigours of MetaField::Int were applied, so no need to relax them.

When I reported this yesterday, I thought maybe `fromform` was called at the end of `MetaField::form_value` to support complex cases of value transformation in, say, compound fields, but doing a quick code search suggest all the complexities of assembling multiple POST parameters into a single scalar or hashref (in Compound, Date, Time, etc.) is done in `$field->form_value_basic`, so that still seems to be the right sort of level to be applying the transformation.

So actually I have this idea. As far as I can see, the architecture of how this all works is:

- `$field->form_value_basic` does the job of turning the POSTed form values into the scalar/hashref expected for the field.
- `$field->form_value_single` then cleans it and returns `undef` if it doesn't like what it sees (currently this only uses the `EPrints::Utils::is_set( $value )` test).
- `$field->form_value_actual` then deals with the single/multiple thing.

`form_value_single` therefore seems to be the natural home for transforming usable values and discarding unusable ones. So it would make the most logical sense to do this:

- Remove the "fromform" call from `MetaField::form_value`.
- Insert the "fromform" call in `MetaField::form_value_single` just before its "is_set" test.
- Replace `MetaField::Int::form_value_basic` with the equivalent override of `MetaField::form_value_single`
    ```perl
    package EPrints::MetaField::Int;
    sub form_value_single
    {
    	my( $self, $session, $basename, $object ) = @_;
    	my $value = $self->SUPER::form_value_single( $session, $basename, $object );
    	return defined $value && $value =~ $self->property( "regexp" ) ? $value : undef;
    }
    ```

What do you think?

**Comment by alex-ball** [comment]
Regarding your testing, I just had a thought that the default regexp for Int is `/-?[0-9]+/`, not `/^-?[0-9]+$/`, so the bug might not trigger if the string you are converting into/out of has a digit somewhere in it.

**Comment by drn05r** [comment]
I have test the changes you suggest, I can see the lookup works as debug in MetaField::Int::form_value_single shows appropriate values but then the value disappears.  I had to make some changes to MetaField::add_input_elements so it did not break for multiple fields where `$value` is provided as a scalar.  The fact I needed to do this suggest there is somewhere else that is not combining the individual values into an arrayref as might be expected,

**Comment by drn05r** [comment]
The problem with trying to use single value tofrom and fromform functions for multiple fields is that this causes problems with `MetaField::render_input_field` as when it calls `toform` it treats single and multiple fields the same.  If you were to modify the code to be able to detect if it was a multiple or single field and behave differently like the code below:
```
        if( defined $self->{toform} )
        {
                if ( $self->{multiple} )
                {
                        my $value_arrayref = [];
                        foreach my $v ( @$value )
                        {
                                $v = $self->call_property( "toform", $v, $session, $obj, $basename );
                                push @$value_arrayref, $v;
                        }
                        $value = $value_arrayref;
                }
                else
                {
                        $value = $self->call_property( "toform", $value, $session, $obj, $basename );
                }
        }
```
Then this would fix this issue but create another problem in `MetaField::ItemRef::get_basic_input_elements` as it does treat single and multiple fields differently.  I have tested commenting out the if/else block as follows:
```
#               if ( $self->get_property("multiple") )
#               {
#                       $raw_value = pop @{
#                               $self->call_property( "fromform", [$value], $session, $obj,
#                                       $basename )
#                       };
#               }
#               else
#               {
                        $raw_value =
                          $self->call_property( "fromform", $value, $session, $obj,
                                $basename );
#               }
````
This fixes the issue so you can use the single `toform` and `fromform` functions with a multiple field.  However, if anyone had coded their own `toform` and `fromform` methods for a multiple field.  If we made these changes, their functions would break and they would need to rewrite them.  

Therefore, although it is annoying to need different functions depending on whether the field is single or multiple, I cannot see how we can sensibly change the code to do so.

**Comment by alex-ball** [comment]
The two things are independent, so there's no programming reason why changing where "fromform" is called should necessitate changing how "toform" works. But from a human perspective, it is more intuitive that they should be proper inverses of each other.

The inverse of calling "fromform" as early as possible after reading the form is to call "toform" as late as possible when rendering the form. So, just as I suggested moving the "fromform" call from `$field->form_value` to `$field->form_value_single`, in the inverse workflow:

- Remove the "toform" call from `MetaField::render_input_field`
- Insert the "toform" call at the start of `MetaField::get_input_elements_single`

As far as I can see the latter isn't overridden anywhere, and where the former is overridden (in MetaField::Image) the "toform" mechanism isn't used and `get_input_elements_single` isn't called, so that won't be affected.

Just as `form_value_single` happens just after the simple/compound issue is handled in `form_value_basic`, `get_input_elements_single` happens just before the simple/compound issue is handled in `get_basic_input_elements`, so that inversion works nicely as well.

If the objection to changing to single-value "tofrom" and "fromform" functions is that it would break configurations where people have coded multiple-value "tofrom" and "fromform" functions, then yes, that's true by definition. But the fact remains that one of the compelling reasons for the "toform"/"fromform" functions is to translate Itemref IDs to and from human-readable strings, and this cannot work if non-integer values are thrown away before running the function that turns the non-integer values into integers.

The elegant solution is to leave the calls to "toform" and "fromform" where they are, but deprecate them. Insert "to_form" and "from_form" calls in the new positions, and in the documentation say that new code should use these instead.

**Comment by alex-ball** [comment]
Just to be clear for anyone following along at home, where "fromform" is called in `MetaField::ItemRef::get_basic_input_elements`, the `$value` is scalar at this point, so the `multiple` test is ensuring that a "fromform" function that expects an arrayref is fed the `$value` wrapped up in one, and the transformed value is popped out of the return value instead of being used directly.

A hypothetical "from_form" that always expects a scalar wouldn't need this, so would make for simplified and cleaner code at this point. But supporting the deprecation would of course complicate things.

```perl
if ( defined $value && !defined $self->{get_item} )
{
	if ( defined $self->{from_form} )
	{
		$raw_value =
			$self->call_property( "from_form", $value, $session, $obj,
			$basename );
	}
	elsif ( defined $self->{fromform} )
	{
		if ( $self->get_property("multiple") )
		{
			$raw_value = pop @{
				$self->call_property( "fromform", [$value], $session, $obj,
					$basename )
			};
		}
		else
		{
			$raw_value =
				$self->call_property( "fromform", $value, $session, $obj,
				$basename );
		}
	}
}
```

**Comment by alex-ball** [comment]
As a humorous aside, you know one of my suggestions in the original post was passing the unconverted value as an extra parameter? If the "toform" conversion happens in `get_input_elements_single`, that would be a dead simple hack and would avoid the round-tripping:

```perl
package EPrints::MetaField::Itemref;
sub get_input_elements_single
{
	my( $self, $session, $value, $basename, $staff, $obj, $one_field_component ) = @_;
	my $raw_value = $value;
	if( defined $self->{to_form} )
	{
		$value = $self->call_property( "to_form", $raw_value, $session, $obj, $basename );
	}
	return $self->get_basic_input_elements( 
		$session, $value, $basename, $staff, $obj, $one_field_component, $raw_value );
}
sub get_basic_input_elements
{
	my( $self, $session, $value, $basename, $staff, $obj, $one_field_component, $raw_value ) = @_;
	...
}
```

Not a serious suggestion at this point, but it made me smile.

**Comment by drn05r** [comment]
[501bee2](https://github.com/eprints/eprints3.4/commit/501bee2442703de25176de871d13b900c16928ea) should have fixed the issues experienced.

**Comment by alex-ball** [comment]
I've run into a bug which I've tracked down to this new code in `MetaField::form_value_single`:

https://github.com/eprints/eprints3.4/blob/d9189c31de5950266611e4cd48ff74aebc3dee49/perl_lib/EPrints/MetaField.pm#L1883-L1890

If the `fromform` function is expecting a simple scalar value, and the value isn't recognised (e.g. the value is blank), the `eval` block will evaluate false, so the code will try again, this time passing an arrayref. In this context, the arrayref might get interpreted as 1 (the length), and translate to some unexpected value. (This did actually happen to me.)

If `fromform` is expecting an arrayref, presumably it will also be yielding an arrayref, so on line 1888 won't the `$value` will end up being "ARRAY(0x...)" instead of the translated single value?

Both of these could be solved if the code at 1888 guardedly attempted to pop a simple scalar out of the returned arrayref, as is done in `MetaField::Itemref::get_basic_input_elements`.

A workaround for a simple-scalar `fromform` function is to add a test so that it returns `undef` if passed an arrayref as the value.
