### ISSUE TITLE
bad link in batch edit listing

### ISSUE THREAD

**Issue by Pfiffikus** [eprints/eprints3.4#56]
The link of the partial listing points to `/id/eprint/<eprintid>`, which is _not_ valid for _all_ states.

I think the link should also point to `/cgi/users/home?screen=EPrint::View&eprintid=<eprintid>` as usual for a result listing.

**Comment by drn05r** [comment]
I have done a search for all items under review and then done a batch edit.  I have found that in the partial listing items that are in the user workarea or under review have no link but those that are live have a /id/eprint/<eprintid> link.  I see no specific need to change this as the user can inspect all the items on the search results page (where the appropriate link is used) before they go to batch edit.  The partial listing is just to give an overview of items not a definitive resource for the inspection of items

**Comment by drn05r** [comment]
Closing as current GitHub HEAD does not have this issue, as non-live items do not have links in their citations on the batch edit page.
