### ISSUE TITLE
EPM sources broken

### ISSUE THREAD

**Issue by jesusbagpuss** [eprints/eprints3.4#58]
The default config that deals with EPM sources is mis-matched:
In the config file, `$c->{epm_sources}` is used:
https://github.com/eprints/eprints3.4/blob/1dc46958229115ac8698f2e886efac4ba2ebd618/ingredients/bazaar/cfg.d/epm.pl#L12-L19

Whereas in the Bazaar screen, `$c->{epm}->{sources}` is used:
https://github.com/eprints/eprints3.4/blob/1dc46958229115ac8698f2e886efac4ba2ebd618/ingredients/bazaar/plugins/EPrints/EPM/Source.pm#L36-L39

Both deal with the case that there are no sources by adding the default bazaar.eprints.org URL.

Not sure whether `$c->{epm_sources}` or `$c->{epm}->{sources}` is the more preferable fix..?

**Comment by drn05r** [comment]
Yes this looks like an oversight.  When dealing with field names _ and separate sub hashrefs are somewhat interchangeable but this is not the case with config options.
