### ISSUE TITLE
pagerange couldn't handle multiple hyphen

### ISSUE THREAD

**Issue by Pfiffikus** [eprints/eprints3.4#60]
The input of A-1–A-7 is possible, but the division for the next editing fails and allows (even accidentally) saving of 'A–1'.

**Comment by drn05r** [comment]
The fix I have applied will not work in all situations but does fix the issue above.  An example where it would not work is if the from page was A-1-2 and the to page was A-2.  I cannot imagine such situations being that common but without completely rewriting how page ranges are stored and all the backwards compatability that would nee to be introduced, this solution I think is the best available.
