### ISSUE TITLE
Bazaar inaccessible behind HTTP proxy

### ISSUE THREAD

**Issue by alex-ball** [eprints/eprints3.4#7]
Running EPrints 3.4 with Perl 5.22 behind a HTTP proxy (and using HTTPS), I find that on the Admin::EPM screen, the list of available packages fails to load.

Adding the following lines to `ingredients/bazaar/plugins/EPrints/EPM/Source.pm` solves that problem:

```perl
use strict;
use LWP::Protocol::https; # <-- Add this line.
#...
sub accolades
{
        my( $_ua, $_base_url ) = @_;
 
        my $ua = ( $_ua ) ? $_ua : LWP::UserAgent->new;
        $ua->env_proxy;  # <-- Add this line.
```

I have not put this as a pull request as the actual code will need to be more carefully changed (e.g. dependent on Perl version) and I can't guarantee this is a complete fix as there may be related problems I haven't hit yet.

**Comment by drn05r** [comment]
I also suspect that LWP::Protocol::https will not always be installed on a repositories server, so will cause dependency issue on future upgrades for a problem that only presents itself if you are using an HTTP proxy.  

I can see there is the DEB liblwp-protocol-https-perl and the RPM perl-LWP-Protocol-https, so it should be fairly easy to install.

**Comment by drn05r** [comment]
I will make sure 3.4.2 packages include the package dependencies and otherwise update install instructions.

**Comment by drn05r** [comment]
LWP::Protocol::https is already used by EPrints and you will get a warning message on the Bazaar page if it is not installed telling you to install it.  use_proxy is already used when loading the the Bazaar page itself, so adding it for loading accolades should not make any difference and make this consistent.

Installing the DEB/RPM needed for LWP::Protocol::https have been added to the dependencies on the appropriate EPrints wiki pages.  They will also be added to any future eprints DEB or RPMs produced.
