### ISSUE TITLE
Rationalise filenames on uploads 

### ISSUE THREAD

**Issue by drn05r** [eprints/eprints3.4#74]
Parts of the core cannot cope with filenames with spaces in, (e.g. images with spaces in their filenames fail to have thumbnails produced).  This is down to poorly implemented legacy code.
However, rather than fixing this code a better catchall would be to rename the files to something more manageable upon upload.  This would save having to also get 3rd party extensions fixed.

One common solution for web-based CMS is to rename the files to some numeric reference (e.g. 245959345.pdf, or even no file extension) and its proper filename is already stored in the database anyway, (e.g. "my thesis.pdf").  The numeric rerference could used the fileid value, as this will alway be unique.

Another solution would be to just replace all non-permitted characters (e.g. space but also non-ascii characters with an agreed character (e.g. underscore '_').  This could potential have the issue of tryig to store two files in the same directory with the same filename.  Although the chances of this are very low.  First it unusual for a document directory to have multiple files added to it, as this is a very nice feature and then the chances of the sanitisation to remove non-permitted characters making two these files have the same filename is even less likely.
 
Either way a tool is also needed to dance over the existing data in a repository to rename files.

**Comment by drn05r** [comment]
Also need to consider if these may affect SWORD deposits

**Comment by Pfiffikus** [comment]
> Parts of the core cannot cope with "Windows filenames" ...

even some versions of backup systems made trouble ;(

I prefer the first proposal, assuming the original name will be used for downloads! I see no advantage of removing the file extension, but fear the information loss for any action on file system level.

**Comment by drn05r** [comment]
I believe 10th October commit fixes this issue.
