### ISSUE TITLE
Radio buttons (as well as checkboxes) need id != name

### ISSUE THREAD

**Issue by alex-ball** [eprints/eprints3.4#87]
When rendering a set of radio buttons using `EPrints::Repository::render_noenter_input_field` (or similar), each `<input>` element is given the same `id`, which is invalid and stops `<label>`s being associated with the correct `<input>`.

For example, in `EPrints::Metafield::Set`:
https://github.com/eprints/eprints3.4/blob/220feb2a51078b93f89b103744334a16322e6a8b/perl_lib/EPrints/MetaField/Set.pm#L300-L306

This gets rendered like this:

```html
<input type="radio" name="c1_usertype" id="c1_usertype" value="user" ...>
<input type="radio" name="c1_usertype" id="c1_usertype" value="editor" ...>
<input type="radio" name="c1_usertype" id="c1_usertype" value="admin" ...>
```

because the `id` value given in the code is overwritten by `EPrints::XHTML::input_field`:
https://github.com/eprints/eprints3.4/blob/220feb2a51078b93f89b103744334a16322e6a8b/perl_lib/EPrints/XHTML.pm#L174-L193

The test on line 181 should be satisfied by `type => 'radio'` as well as `type => 'checkbox'`. More generally, it may cause less surprise to the developer if `$noid` gets set to `1` if `id` is already set in `@opts`.

**Comment by drn05r** [comment]
This is being worked on as part of the Accessibility Roadmap and will be fixed as part of the 3.4.3 release.
