### ISSUE TITLE
Provide Datepicker MetaField to reduce human error on date input

### ISSUE THREAD

**Issue by drn05r** [eprints/eprints3.4#93]
How EPrints currently supports date entry means users are liable to enter impossible dates where the day of the month is higher than the number of days in that particular month (e.g. 31st September).  Therefore, a Datepicker MetaField would prevent users from being able to select an invalid date.

**Comment by mpbraendle** [comment]
Datepicker is one solution, but may not prohibit impossible dates. Preferable would be validation code in Metafield/Date.pm that marks invalid dates.
